// dart format width=80
// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
//
import 'package:drift/drift.dart';
import 'package:drift/internal/migrations.dart';
import 'schema_v38.dart' as v38;
import 'schema_v39.dart' as v39;
import 'schema_v40.dart' as v40;
import 'schema_v41.dart' as v41;
import 'schema_v42.dart' as v42;
import 'schema_v43.dart' as v43;
import 'schema_v44.dart' as v44;
import 'schema_v45.dart' as v45;
import 'schema_v46.dart' as v46;

class GeneratedHelper implements SchemaInstantiationHelper {
  @override
  GeneratedDatabase databaseForVersion(QueryExecutor db, int version) {
    switch (version) {
      case 38:
        return v38.DatabaseAtV38(db);
      case 39:
        return v39.DatabaseAtV39(db);
      case 40:
        return v40.DatabaseAtV40(db);
      case 41:
        return v41.DatabaseAtV41(db);
      case 42:
        return v42.DatabaseAtV42(db);
      case 43:
        return v43.DatabaseAtV43(db);
      case 44:
        return v44.DatabaseAtV44(db);
      case 45:
        return v45.DatabaseAtV45(db);
      case 46:
        return v46.DatabaseAtV46(db);
      default:
        throw MissingSchemaException(version, versions);
    }
  }

  static const versions = const [38, 39, 40, 41, 42, 43, 44, 45, 46];
}
