// dart format width=80
// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
//
import 'package:drift/drift.dart';
import 'package:drift/internal/migrations.dart';
import 'schema_v38.dart' as v38;
import 'schema_v39.dart' as v39;
import 'schema_v40.dart' as v40;

class GeneratedHelper implements SchemaInstantiationHelper {
  @override
  GeneratedDatabase databaseForVersion(QueryExecutor db, int version) {
    switch (version) {
      case 38:
        return v38.DatabaseAtV38(db);
      case 39:
        return v39.DatabaseAtV39(db);
      case 40:
        return v40.DatabaseAtV40(db);
      default:
        throw MissingSchemaException(version, versions);
    }
  }

  static const versions = const [38, 39, 40];
}
