// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema39 extends i0.VersionedSchema {
  Schema39({required super.database}) : super(version: 39);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    nations,
    players,
    careers,
    competitions,
    qualifyingGroups,
    groupMembers,
    fixtures,
    tactics,
    lineupSlots,
    callUps,
    callUpDrafts,
    trainingCampChoices,
    goalEvents,
    honours,
    drawsWatched,
    playerAbsences,
    rankPoints,
    seedRankings,
    rankingReleases,
    achievements,
    appearances,
    tournamentAppearances,
    messages,
    careerStints,
    playerRatings,
    federationInvestments,
    matchTeamStats,
    nationsCupTiers,
    naturalizedPlayers,
    tacticFamiliarities,
    pressAnswers,
  ];
  late final Shape0 nations = Shape0(
    source: i0.VersionedTable(
      entityName: 'nations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 players = Shape1(
    source: i0.VersionedTable(
      entityName: 'players',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_8,
        _column_1,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 careers = Shape2(
    source: i0.VersionedTable(
      entityName: 'careers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 competitions = Shape3(
    source: i0.VersionedTable(
      entityName: 'competitions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_15,
        _column_25,
        _column_3,
        _column_1,
        _column_26,
        _column_27,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 qualifyingGroups = Shape4(
    source: i0.VersionedTable(
      entityName: 'qualifying_groups',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_15, _column_28, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 groupMembers = Shape5(
    source: i0.VersionedTable(
      entityName: 'group_members',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(group_id, nation_id)'],
      columns: [_column_29, _column_30],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 fixtures = Shape6(
    source: i0.VersionedTable(
      entityName: 'fixtures',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_15,
        _column_25,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 tactics = Shape7(
    source: i0.VersionedTable(
      entityName: 'tactics',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id)'],
      columns: [
        _column_25,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 lineupSlots = Shape8(
    source: i0.VersionedTable(
      entityName: 'lineup_slots',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, slot)'],
      columns: [_column_25, _column_52, _column_53],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 callUps = Shape9(
    source: i0.VersionedTable(
      entityName: 'call_ups',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, player_id)'],
      columns: [_column_25, _column_54],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 callUpDrafts = Shape10(
    source: i0.VersionedTable(
      entityName: 'call_up_drafts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, draft_key, player_id)'],
      columns: [_column_25, _column_55, _column_54],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 trainingCampChoices = Shape11(
    source: i0.VersionedTable(
      entityName: 'training_camp_choices',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, cycle, tournament)'],
      columns: [_column_25, _column_56, _column_57, _column_58, _column_59],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 goalEvents = Shape12(
    source: i0.VersionedTable(
      entityName: 'goal_events',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_15,
        _column_25,
        _column_31,
        _column_60,
        _column_30,
        _column_54,
        _column_61,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 honours = Shape13(
    source: i0.VersionedTable(
      entityName: 'honours',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_15,
        _column_25,
        _column_62,
        _column_63,
        _column_64,
        _column_65,
        _column_66,
        _column_67,
        _column_68,
        _column_69,
        _column_70,
        _column_71,
        _column_72,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 drawsWatched = Shape14(
    source: i0.VersionedTable(
      entityName: 'draws_watched',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, cycle, kind)'],
      columns: [_column_25, _column_56, _column_73],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 playerAbsences = Shape15(
    source: i0.VersionedTable(
      entityName: 'player_absences',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, player_id)'],
      columns: [_column_25, _column_54, _column_74, _column_75, _column_76],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape16 rankPoints = Shape16(
    source: i0.VersionedTable(
      entityName: 'rank_points',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, nation_id)'],
      columns: [_column_25, _column_30, _column_77],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape17 seedRankings = Shape17(
    source: i0.VersionedTable(
      entityName: 'seed_rankings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, cycle, nation_id)'],
      columns: [_column_25, _column_56, _column_30, _column_78],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape18 rankingReleases = Shape18(
    source: i0.VersionedTable(
      entityName: 'ranking_releases',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, published_on)'],
      columns: [
        _column_25,
        _column_79,
        _column_27,
        _column_80,
        _column_81,
        _column_82,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape19 achievements = Shape19(
    source: i0.VersionedTable(
      entityName: 'achievements',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, achievement_id)'],
      columns: [_column_25, _column_83, _column_84],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape20 appearances = Shape20(
    source: i0.VersionedTable(
      entityName: 'appearances',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, player_id)'],
      columns: [_column_25, _column_30, _column_54, _column_85],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape21 tournamentAppearances = Shape21(
    source: i0.VersionedTable(
      entityName: 'tournament_appearances',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, competition_id, player_id)'],
      columns: [
        _column_25,
        _column_86,
        _column_30,
        _column_54,
        _column_87,
        _column_88,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape22 messages = Shape22(
    source: i0.VersionedTable(
      entityName: 'messages',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(career_id, dedup_key)'],
      columns: [
        _column_15,
        _column_25,
        _column_89,
        _column_90,
        _column_91,
        _column_92,
        _column_62,
        _column_93,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape23 careerStints = Shape23(
    source: i0.VersionedTable(
      entityName: 'career_stints',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, cycle)'],
      columns: [_column_25, _column_56, _column_30],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape24 playerRatings = Shape24(
    source: i0.VersionedTable(
      entityName: 'player_ratings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, fixture_id, player_id)'],
      columns: [
        _column_25,
        _column_60,
        _column_54,
        _column_80,
        _column_94,
        _column_95,
        _column_96,
        _column_97,
        _column_98,
        _column_74,
        _column_99,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape25 federationInvestments = Shape25(
    source: i0.VersionedTable(
      entityName: 'federation_investments',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, cycle)'],
      columns: [
        _column_25,
        _column_56,
        _column_100,
        _column_101,
        _column_102,
        _column_103,
        _column_104,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape26 matchTeamStats = Shape26(
    source: i0.VersionedTable(
      entityName: 'match_team_stats',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, fixture_id)'],
      columns: [
        _column_25,
        _column_60,
        _column_105,
        _column_106,
        _column_107,
        _column_108,
        _column_109,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape27 nationsCupTiers = Shape27(
    source: i0.VersionedTable(
      entityName: 'nations_cup_tiers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, nation_id)'],
      columns: [_column_25, _column_30, _column_110],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape28 naturalizedPlayers = Shape28(
    source: i0.VersionedTable(
      entityName: 'naturalized_players',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, player_id)'],
      columns: [_column_25, _column_54, _column_111, _column_56, _column_112],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape29 tacticFamiliarities = Shape29(
    source: i0.VersionedTable(
      entityName: 'tactic_familiarities',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, formation)'],
      columns: [_column_25, _column_44, _column_113, _column_114, _column_115],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape30 pressAnswers = Shape30(
    source: i0.VersionedTable(
      entityName: 'press_answers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_15,
        _column_25,
        _column_56,
        _column_116,
        _column_117,
        _column_118,
        _column_119,
        _column_120,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get code =>
      columnsByName['code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get confederation =>
      columnsByName['confederation']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get ranking =>
      columnsByName['ranking']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isFreeDemo =>
      columnsByName['is_free_demo']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get primaryColor =>
      columnsByName['primary_color']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get secondaryColor =>
      columnsByName['secondary_color']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'code',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'confederation',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_4(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'ranking',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_free_demo',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_free_demo IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'primary_color',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'#1E88E5\'',
      defaultValue: const i1.CustomExpression('\'#1E88E5\''),
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'secondary_color',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'#FFFFFF\'',
      defaultValue: const i1.CustomExpression('\'#FFFFFF\''),
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get nationId =>
      columnsByName['nation_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get age =>
      columnsByName['age']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get position =>
      columnsByName['position']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get physical =>
      columnsByName['physical']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get technical =>
      columnsByName['technical']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get stamina =>
      columnsByName['stamina']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get club =>
      columnsByName['club']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'nation_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES nations(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'age',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'position',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'physical',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'technical',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_13(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'stamina',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'club',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'Free agent\'',
      defaultValue: const i1.CustomExpression('\'Free agent\''),
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get managerName =>
      columnsByName['manager_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get nationId =>
      columnsByName['nation_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get rngSeed =>
      columnsByName['rng_seed']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get inGameDate =>
      columnsByName['in_game_date']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get cyclePointer =>
      columnsByName['cycle_pointer']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastPlayedAt =>
      columnsByName['last_played_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get budget =>
      columnsByName['budget']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get captainPlayerId =>
      columnsByName['captain_player_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'manager_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'nation_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES nations(id)',
    );
i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'rng_seed',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'in_game_date',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'cycle_pointer',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_played_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'budget',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'captain_player_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get careerId =>
      columnsByName['career_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get confederation =>
      columnsByName['confederation']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get cycle =>
      columnsByName['cycle']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'career_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES careers(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'worldCupQualifying\'',
      defaultValue: const i1.CustomExpression('\'worldCupQualifying\''),
    );
i1.GeneratedColumn<int> _column_27(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'cycle',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get competitionId =>
      columnsByName['competition_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'competition_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES competitions(id)ON DELETE CASCADE',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get groupId =>
      columnsByName['group_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get nationId =>
      columnsByName['nation_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_29(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'group_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES qualifying_groups(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_30(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'nation_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get careerId =>
      columnsByName['career_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get competitionId =>
      columnsByName['competition_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get groupId =>
      columnsByName['group_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get matchday =>
      columnsByName['matchday']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get date =>
      columnsByName['date']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get homeNationId =>
      columnsByName['home_nation_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get awayNationId =>
      columnsByName['away_nation_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get homeScore =>
      columnsByName['home_score']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get awayScore =>
      columnsByName['away_score']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get played =>
      columnsByName['played']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get round =>
      columnsByName['round']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get afterExtraTime =>
      columnsByName['after_extra_time']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get homePenalties =>
      columnsByName['home_penalties']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get awayPenalties =>
      columnsByName['away_penalties']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_31(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'competition_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES competitions(id)',
    );
i1.GeneratedColumn<int> _column_32(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'group_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES qualifying_groups(id)',
    );
i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'matchday',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'date',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_35(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'home_nation_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_36(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'away_nation_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_37(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'home_score',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_38(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'away_score',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'played',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (played IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'round',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_41(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'after_extra_time',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (after_extra_time IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_42(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'home_penalties',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_43(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'away_penalties',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get careerId =>
      columnsByName['career_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get formation =>
      columnsByName['formation']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get playstyle =>
      columnsByName['playstyle']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get mentality =>
      columnsByName['mentality']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get pressing =>
      columnsByName['pressing']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get tempo =>
      columnsByName['tempo']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get width =>
      columnsByName['width']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get defensiveLine =>
      columnsByName['defensive_line']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get directness =>
      columnsByName['directness']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'formation',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'playstyle',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'custom\'',
      defaultValue: const i1.CustomExpression('\'custom\''),
    );
i1.GeneratedColumn<int> _column_46(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'mentality',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 50',
      defaultValue: const i1.CustomExpression('50'),
    );
i1.GeneratedColumn<int> _column_47(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'pressing',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 50',
      defaultValue: const i1.CustomExpression('50'),
    );
i1.GeneratedColumn<int> _column_48(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'tempo',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 50',
      defaultValue: const i1.CustomExpression('50'),
    );
i1.GeneratedColumn<int> _column_49(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'width',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 50',
      defaultValue: const i1.CustomExpression('50'),
    );
i1.GeneratedColumn<int> _column_50(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'defensive_line',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 50',
      defaultValue: const i1.CustomExpression('50'),
    );
i1.GeneratedColumn<int> _column_51(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'directness',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 50',
      defaultValue: const i1.CustomExpression('50'),
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get careerId =>
      columnsByName['career_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get slot =>
      columnsByName['slot']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get playerId =>
      columnsByName['player_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_52(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'slot',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_53(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'player_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get careerId =>
      columnsByName['career_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get playerId =>
      columnsByName['player_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_54(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'player_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get careerId =>
      columnsByName['career_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get draftKey =>
      columnsByName['draft_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get playerId =>
      columnsByName['player_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_55(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'draft_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get careerId =>
      columnsByName['career_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get cycle =>
      columnsByName['cycle']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get tournament =>
      columnsByName['tournament']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get hostId =>
      columnsByName['host_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get campIndex =>
      columnsByName['camp_index']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_56(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'cycle',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_57(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tournament',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_58(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'host_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_59(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'camp_index',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get careerId =>
      columnsByName['career_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get competitionId =>
      columnsByName['competition_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fixtureId =>
      columnsByName['fixture_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get nationId =>
      columnsByName['nation_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get playerId =>
      columnsByName['player_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get minute =>
      columnsByName['minute']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_60(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'fixture_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES fixtures(id)',
    );
i1.GeneratedColumn<int> _column_61(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'minute',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get careerId =>
      columnsByName['career_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get year =>
      columnsByName['year']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get competition =>
      columnsByName['competition']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get championId =>
      columnsByName['champion_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get runnerUpId =>
      columnsByName['runner_up_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get thirdId =>
      columnsByName['third_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get thirdId2 =>
      columnsByName['third_id2']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get hostId =>
      columnsByName['host_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get finalHomeScore =>
      columnsByName['final_home_score']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get finalAwayScore =>
      columnsByName['final_away_score']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get topScorerName =>
      columnsByName['top_scorer_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get topScorerGoals =>
      columnsByName['top_scorer_goals']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_62(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'year',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_63(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'competition',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_64(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'champion_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_65(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'runner_up_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_66(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'third_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_67(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'third_id2',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_68(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'host_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_69(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'final_home_score',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_70(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'final_away_score',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_71(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'top_scorer_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_72(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'top_scorer_goals',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape14 extends i0.VersionedTable {
  Shape14({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get careerId =>
      columnsByName['career_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get cycle =>
      columnsByName['cycle']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_73(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape15 extends i0.VersionedTable {
  Shape15({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get careerId =>
      columnsByName['career_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get playerId =>
      columnsByName['player_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get yellows =>
      columnsByName['yellows']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get banMatches =>
      columnsByName['ban_matches']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get injuryMatches =>
      columnsByName['injury_matches']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_74(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'yellows',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_75(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'ban_matches',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_76(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'injury_matches',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape16 extends i0.VersionedTable {
  Shape16({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get careerId =>
      columnsByName['career_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get nationId =>
      columnsByName['nation_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get points =>
      columnsByName['points']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_77(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'points',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape17 extends i0.VersionedTable {
  Shape17({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get careerId =>
      columnsByName['career_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get cycle =>
      columnsByName['cycle']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get nationId =>
      columnsByName['nation_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get rank =>
      columnsByName['rank']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_78(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'rank',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape18 extends i0.VersionedTable {
  Shape18({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get careerId =>
      columnsByName['career_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get publishedOn =>
      columnsByName['published_on']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get cycle =>
      columnsByName['cycle']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get nationId =>
      columnsByName['nation_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get playerRank =>
      columnsByName['player_rank']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get leaderNationId =>
      columnsByName['leader_nation_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_79(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'published_on',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_80(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'nation_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_81(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'player_rank',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_82(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'leader_nation_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape19 extends i0.VersionedTable {
  Shape19({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get careerId =>
      columnsByName['career_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get achievementId =>
      columnsByName['achievement_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get earnedYear =>
      columnsByName['earned_year']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_83(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'achievement_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_84(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'earned_year',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape20 extends i0.VersionedTable {
  Shape20({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get careerId =>
      columnsByName['career_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get nationId =>
      columnsByName['nation_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get playerId =>
      columnsByName['player_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get count =>
      columnsByName['count']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_85(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape21 extends i0.VersionedTable {
  Shape21({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get careerId =>
      columnsByName['career_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get competitionId =>
      columnsByName['competition_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get nationId =>
      columnsByName['nation_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get playerId =>
      columnsByName['player_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get starts =>
      columnsByName['starts']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get apps =>
      columnsByName['apps']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_86(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'competition_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_87(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'starts',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_88(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'apps',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape22 extends i0.VersionedTable {
  Shape22({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get careerId =>
      columnsByName['career_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get dedupKey =>
      columnsByName['dedup_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get category =>
      columnsByName['category']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get body =>
      columnsByName['body']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get year =>
      columnsByName['year']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get read =>
      columnsByName['read']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_89(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'dedup_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_90(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'category',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_91(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_92(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'body',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_93(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'read',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (read IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape23 extends i0.VersionedTable {
  Shape23({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get careerId =>
      columnsByName['career_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get cycle =>
      columnsByName['cycle']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get nationId =>
      columnsByName['nation_id']! as i1.GeneratedColumn<int>;
}

class Shape24 extends i0.VersionedTable {
  Shape24({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get careerId =>
      columnsByName['career_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fixtureId =>
      columnsByName['fixture_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get playerId =>
      columnsByName['player_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get nationId =>
      columnsByName['nation_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get rating =>
      columnsByName['rating']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get goals =>
      columnsByName['goals']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get assists =>
      columnsByName['assists']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get cleanSheet =>
      columnsByName['clean_sheet']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get motm =>
      columnsByName['motm']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get yellows =>
      columnsByName['yellows']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get reds =>
      columnsByName['reds']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<double> _column_94(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'rating',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_95(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'goals',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_96(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'assists',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_97(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'clean_sheet',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (clean_sheet IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_98(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'motm',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (motm IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_99(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'reds',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape25 extends i0.VersionedTable {
  Shape25({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get careerId =>
      columnsByName['career_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get cycle =>
      columnsByName['cycle']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get youth =>
      columnsByName['youth']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get commercial =>
      columnsByName['commercial']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get medical =>
      columnsByName['medical']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get naturalization =>
      columnsByName['naturalization']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get boardRelations =>
      columnsByName['board_relations']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_100(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'youth',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_101(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'commercial',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_102(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'medical',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_103(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'naturalization',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_104(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'board_relations',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape26 extends i0.VersionedTable {
  Shape26({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get careerId =>
      columnsByName['career_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fixtureId =>
      columnsByName['fixture_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get homeShots =>
      columnsByName['home_shots']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get awayShots =>
      columnsByName['away_shots']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get homePossession =>
      columnsByName['home_possession']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get homeXg =>
      columnsByName['home_xg']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get awayXg =>
      columnsByName['away_xg']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<int> _column_105(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'home_shots',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_106(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'away_shots',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_107(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'home_possession',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 50',
      defaultValue: const i1.CustomExpression('50'),
    );
i1.GeneratedColumn<double> _column_108(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'home_xg',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL DEFAULT 0.0',
      defaultValue: const i1.CustomExpression('0.0'),
    );
i1.GeneratedColumn<double> _column_109(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'away_xg',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL DEFAULT 0.0',
      defaultValue: const i1.CustomExpression('0.0'),
    );

class Shape27 extends i0.VersionedTable {
  Shape27({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get careerId =>
      columnsByName['career_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get nationId =>
      columnsByName['nation_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get tier =>
      columnsByName['tier']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_110(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'tier',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape28 extends i0.VersionedTable {
  Shape28({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get careerId =>
      columnsByName['career_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get playerId =>
      columnsByName['player_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sourceNationId =>
      columnsByName['source_nation_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get cycle =>
      columnsByName['cycle']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_111(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'source_nation_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_112(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'pending\'',
      defaultValue: const i1.CustomExpression('\'pending\''),
    );

class Shape29 extends i0.VersionedTable {
  Shape29({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get careerId =>
      columnsByName['career_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get formation =>
      columnsByName['formation']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get familiarity =>
      columnsByName['familiarity']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get predictability =>
      columnsByName['predictability']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get lastPlanKey =>
      columnsByName['last_plan_key']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<double> _column_113(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'familiarity',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL DEFAULT 0.0',
      defaultValue: const i1.CustomExpression('0.0'),
    );
i1.GeneratedColumn<double> _column_114(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'predictability',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL DEFAULT 0.0',
      defaultValue: const i1.CustomExpression('0.0'),
    );
i1.GeneratedColumn<int> _column_115(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_plan_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape30 extends i0.VersionedTable {
  Shape30({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get careerId =>
      columnsByName['career_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get cycle =>
      columnsByName['cycle']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get questionKey =>
      columnsByName['question_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tone =>
      columnsByName['tone']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get moraleDelta =>
      columnsByName['morale_delta']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get boardDelta =>
      columnsByName['board_delta']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get answeredAt =>
      columnsByName['answered_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_116(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'question_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_117(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tone',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_118(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'morale_delta',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_119(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'board_delta',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_120(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'answered_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

final class Schema40 extends i0.VersionedSchema {
  Schema40({required super.database}) : super(version: 40);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    nations,
    players,
    careers,
    competitions,
    qualifyingGroups,
    groupMembers,
    fixtures,
    tactics,
    lineupSlots,
    callUps,
    callUpDrafts,
    trainingCampChoices,
    goalEvents,
    honours,
    drawsWatched,
    playerAbsences,
    rankPoints,
    seedRankings,
    rankingReleases,
    achievements,
    appearances,
    tournamentAppearances,
    messages,
    careerStints,
    playerRatings,
    federationInvestments,
    matchTeamStats,
    nationsCupTiers,
    naturalizedPlayers,
    tacticFamiliarities,
    pressAnswers,
    playerHonours,
  ];
  late final Shape0 nations = Shape0(
    source: i0.VersionedTable(
      entityName: 'nations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 players = Shape1(
    source: i0.VersionedTable(
      entityName: 'players',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_8,
        _column_1,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 careers = Shape2(
    source: i0.VersionedTable(
      entityName: 'careers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 competitions = Shape3(
    source: i0.VersionedTable(
      entityName: 'competitions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_15,
        _column_25,
        _column_3,
        _column_1,
        _column_26,
        _column_27,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 qualifyingGroups = Shape4(
    source: i0.VersionedTable(
      entityName: 'qualifying_groups',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_15, _column_28, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 groupMembers = Shape5(
    source: i0.VersionedTable(
      entityName: 'group_members',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(group_id, nation_id)'],
      columns: [_column_29, _column_30],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 fixtures = Shape6(
    source: i0.VersionedTable(
      entityName: 'fixtures',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_15,
        _column_25,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 tactics = Shape7(
    source: i0.VersionedTable(
      entityName: 'tactics',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id)'],
      columns: [
        _column_25,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 lineupSlots = Shape8(
    source: i0.VersionedTable(
      entityName: 'lineup_slots',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, slot)'],
      columns: [_column_25, _column_52, _column_53],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 callUps = Shape9(
    source: i0.VersionedTable(
      entityName: 'call_ups',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, player_id)'],
      columns: [_column_25, _column_54],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 callUpDrafts = Shape10(
    source: i0.VersionedTable(
      entityName: 'call_up_drafts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, draft_key, player_id)'],
      columns: [_column_25, _column_55, _column_54],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 trainingCampChoices = Shape11(
    source: i0.VersionedTable(
      entityName: 'training_camp_choices',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, cycle, tournament)'],
      columns: [_column_25, _column_56, _column_57, _column_58, _column_59],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 goalEvents = Shape12(
    source: i0.VersionedTable(
      entityName: 'goal_events',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_15,
        _column_25,
        _column_31,
        _column_60,
        _column_30,
        _column_54,
        _column_61,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 honours = Shape13(
    source: i0.VersionedTable(
      entityName: 'honours',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_15,
        _column_25,
        _column_62,
        _column_63,
        _column_64,
        _column_65,
        _column_66,
        _column_67,
        _column_68,
        _column_69,
        _column_70,
        _column_71,
        _column_72,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 drawsWatched = Shape14(
    source: i0.VersionedTable(
      entityName: 'draws_watched',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, cycle, kind)'],
      columns: [_column_25, _column_56, _column_73],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 playerAbsences = Shape15(
    source: i0.VersionedTable(
      entityName: 'player_absences',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, player_id)'],
      columns: [_column_25, _column_54, _column_74, _column_75, _column_76],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape16 rankPoints = Shape16(
    source: i0.VersionedTable(
      entityName: 'rank_points',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, nation_id)'],
      columns: [_column_25, _column_30, _column_77],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape17 seedRankings = Shape17(
    source: i0.VersionedTable(
      entityName: 'seed_rankings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, cycle, nation_id)'],
      columns: [_column_25, _column_56, _column_30, _column_78],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape18 rankingReleases = Shape18(
    source: i0.VersionedTable(
      entityName: 'ranking_releases',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, published_on)'],
      columns: [
        _column_25,
        _column_79,
        _column_27,
        _column_80,
        _column_81,
        _column_82,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape19 achievements = Shape19(
    source: i0.VersionedTable(
      entityName: 'achievements',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, achievement_id)'],
      columns: [_column_25, _column_83, _column_84],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape20 appearances = Shape20(
    source: i0.VersionedTable(
      entityName: 'appearances',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, player_id)'],
      columns: [_column_25, _column_30, _column_54, _column_85],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape21 tournamentAppearances = Shape21(
    source: i0.VersionedTable(
      entityName: 'tournament_appearances',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, competition_id, player_id)'],
      columns: [
        _column_25,
        _column_86,
        _column_30,
        _column_54,
        _column_87,
        _column_88,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape22 messages = Shape22(
    source: i0.VersionedTable(
      entityName: 'messages',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(career_id, dedup_key)'],
      columns: [
        _column_15,
        _column_25,
        _column_89,
        _column_90,
        _column_91,
        _column_92,
        _column_62,
        _column_93,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape23 careerStints = Shape23(
    source: i0.VersionedTable(
      entityName: 'career_stints',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, cycle)'],
      columns: [_column_25, _column_56, _column_30],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape24 playerRatings = Shape24(
    source: i0.VersionedTable(
      entityName: 'player_ratings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, fixture_id, player_id)'],
      columns: [
        _column_25,
        _column_60,
        _column_54,
        _column_80,
        _column_94,
        _column_95,
        _column_96,
        _column_97,
        _column_98,
        _column_74,
        _column_99,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape25 federationInvestments = Shape25(
    source: i0.VersionedTable(
      entityName: 'federation_investments',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, cycle)'],
      columns: [
        _column_25,
        _column_56,
        _column_100,
        _column_101,
        _column_102,
        _column_103,
        _column_104,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape26 matchTeamStats = Shape26(
    source: i0.VersionedTable(
      entityName: 'match_team_stats',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, fixture_id)'],
      columns: [
        _column_25,
        _column_60,
        _column_105,
        _column_106,
        _column_107,
        _column_108,
        _column_109,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape27 nationsCupTiers = Shape27(
    source: i0.VersionedTable(
      entityName: 'nations_cup_tiers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, nation_id)'],
      columns: [_column_25, _column_30, _column_110],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape28 naturalizedPlayers = Shape28(
    source: i0.VersionedTable(
      entityName: 'naturalized_players',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, player_id)'],
      columns: [_column_25, _column_54, _column_111, _column_56, _column_112],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape29 tacticFamiliarities = Shape29(
    source: i0.VersionedTable(
      entityName: 'tactic_familiarities',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(career_id, formation)'],
      columns: [_column_25, _column_44, _column_113, _column_114, _column_115],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape30 pressAnswers = Shape30(
    source: i0.VersionedTable(
      entityName: 'press_answers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_15,
        _column_25,
        _column_56,
        _column_116,
        _column_117,
        _column_118,
        _column_119,
        _column_120,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape31 playerHonours = Shape31(
    source: i0.VersionedTable(
      entityName: 'player_honours',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(career_id, kind, competition, year, player_id)',
      ],
      columns: [
        _column_25,
        _column_54,
        _column_30,
        _column_73,
        _column_121,
        _column_62,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape31 extends i0.VersionedTable {
  Shape31({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get careerId =>
      columnsByName['career_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get playerId =>
      columnsByName['player_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get nationId =>
      columnsByName['nation_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get competition =>
      columnsByName['competition']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get year =>
      columnsByName['year']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_121(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'competition',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema39 schema) from38To39,
  required Future<void> Function(i1.Migrator m, Schema40 schema) from39To40,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 38:
        final schema = Schema39(database: database);
        final migrator = i1.Migrator(database, schema);
        await from38To39(migrator, schema);
        return 39;
      case 39:
        final schema = Schema40(database: database);
        final migrator = i1.Migrator(database, schema);
        await from39To40(migrator, schema);
        return 40;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema39 schema) from38To39,
  required Future<void> Function(i1.Migrator m, Schema40 schema) from39To40,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from38To39: from38To39, from39To40: from39To40),
);
