/// One real historical tournament final (factual, country-level data only —
/// no player names, to keep the app free of real-person likeness/IP).
///
/// The champion is listed first in the scoreline; equal scores denote a
/// penalty shoot-out win for the champion.
///
/// The scoreline is nullable because not every edition was settled by a final:
/// the early South American Championships were straight round-robins, decided
/// on the table rather than in a one-off match. Those editions carry a champion
/// and a runner-up but no score, and every screen that shows a final already
/// handles a missing scoreline (the honour's own columns are nullable too).
typedef HistoryEdition = ({
  int year,
  String competition,
  /// Every host, primary first. Single-element for an ordinary edition; an
  /// edition that recorded no host at all (the 1975-1983 South America Cups,
  /// played home-and-away with no fixed venue) still carries one element, an
  /// empty string, rather than an empty list.
  List<String> hosts,
  String champion,
  String runnerUp,
  String? third,
  int? finalHome,
  int? finalAway,
});

/// Real World Cup, European Championship and South America Cup history, mapped
/// onto the app's tournament names. Used to seed the records section so it is
/// populated from the start of a save.
abstract final class RealHistory {
  /// Maps historical nation names onto their modern equivalent in the data set.
  static const aliases = <String, String>{
    'West Germany': 'Germany',
    'Soviet Union': 'Russia',
    'Czechoslovakia': 'Czechia',
    'Czech Republic': 'Czechia',
    'Yugoslavia': 'Serbia',
    'Turkey': 'Türkiye',
  };

  /// The two beaten semi-finalists (who share the bronze) for continental-cup
  /// editions. The European Championship and South America Cup rows carry no
  /// single third place in [editions] — they have no third-place match — so
  /// both their bronze medallists are supplied here, keyed `"competition|year"`,
  /// and applied by the history seeder. Names resolve via [aliases].
  static const continentalBronzes = <String, (String, String)>{
    'European Championship|1960': ('Czechoslovakia', 'France'),
    'European Championship|1964': ('Hungary', 'Denmark'),
    'European Championship|1968': ('England', 'Soviet Union'),
    'European Championship|1972': ('Belgium', 'Hungary'),
    'European Championship|1976': ('Netherlands', 'Yugoslavia'),
    'European Championship|1980': ('Czechoslovakia', 'Italy'),
    'European Championship|1984': ('Denmark', 'Portugal'),
    'European Championship|1988': ('West Germany', 'Italy'),
    'European Championship|1992': ('Sweden', 'Netherlands'),
    'European Championship|1996': ('England', 'France'),
    'European Championship|2000': ('Portugal', 'Netherlands'),
    'European Championship|2004': ('Czech Republic', 'Netherlands'),
    'European Championship|2008': ('Russia', 'Turkey'),
    'European Championship|2012': ('Portugal', 'Germany'),
    'European Championship|2016': ('Wales', 'Germany'),
    'European Championship|2020': ('Spain', 'Denmark'),
    'European Championship|2024': ('France', 'Netherlands'),
    'South America Cup|2011': ('Peru', 'Venezuela'),
    'South America Cup|2015': ('Peru', 'Paraguay'),
    'South America Cup|2016': ('Colombia', 'United States'),
    'South America Cup|2019': ('Argentina', 'Chile'),
    'South America Cup|2021': ('Colombia', 'Peru'),
    'South America Cup|2024': ('Uruguay', 'Canada'),
  };

  static const worldChampionship = 'World Championship';
  static const europeanChampionship = 'European Championship';
  static const southAmericaCup = 'South America Cup';
  static const nationsCup = 'Nations Cup';
  static const africanChampionship = 'African Championship';
  static const asianChampionship = 'Asian Championship';
  static const northAmericaCup = 'North America Cup';
  static const oceaniaCup = 'Oceania Cup';

  static const editions = <HistoryEdition>[
    // --- World Cup ---------------------------------------------------------
    (
      year: 1930,
      competition: worldChampionship,
      hosts: ['Uruguay'],
      champion: 'Uruguay',
      runnerUp: 'Argentina',
      third: 'United States',
      finalHome: 4,
      finalAway: 2,
    ),
    (
      year: 1934,
      competition: worldChampionship,
      hosts: ['Italy'],
      champion: 'Italy',
      runnerUp: 'Czechoslovakia',
      third: 'Germany',
      finalHome: 2,
      finalAway: 1,
    ),
    (
      year: 1938,
      competition: worldChampionship,
      hosts: ['France'],
      champion: 'Italy',
      runnerUp: 'Hungary',
      third: 'Brazil',
      finalHome: 4,
      finalAway: 2,
    ),
    (
      year: 1950,
      competition: worldChampionship,
      hosts: ['Brazil'],
      champion: 'Uruguay',
      runnerUp: 'Brazil',
      third: 'Sweden',
      finalHome: 2,
      finalAway: 1,
    ),
    (
      year: 1954,
      competition: worldChampionship,
      hosts: ['Switzerland'],
      champion: 'West Germany',
      runnerUp: 'Hungary',
      third: 'Austria',
      finalHome: 3,
      finalAway: 2,
    ),
    (
      year: 1958,
      competition: worldChampionship,
      hosts: ['Sweden'],
      champion: 'Brazil',
      runnerUp: 'Sweden',
      third: 'France',
      finalHome: 5,
      finalAway: 2,
    ),
    (
      year: 1962,
      competition: worldChampionship,
      hosts: ['Chile'],
      champion: 'Brazil',
      runnerUp: 'Czechoslovakia',
      third: 'Chile',
      finalHome: 3,
      finalAway: 1,
    ),
    (
      year: 1966,
      competition: worldChampionship,
      hosts: ['England'],
      champion: 'England',
      runnerUp: 'West Germany',
      third: 'Portugal',
      finalHome: 4,
      finalAway: 2,
    ),
    (
      year: 1970,
      competition: worldChampionship,
      hosts: ['Mexico'],
      champion: 'Brazil',
      runnerUp: 'Italy',
      third: 'West Germany',
      finalHome: 4,
      finalAway: 1,
    ),
    (
      year: 1974,
      competition: worldChampionship,
      hosts: ['West Germany'],
      champion: 'West Germany',
      runnerUp: 'Netherlands',
      third: 'Poland',
      finalHome: 2,
      finalAway: 1,
    ),
    (
      year: 1978,
      competition: worldChampionship,
      hosts: ['Argentina'],
      champion: 'Argentina',
      runnerUp: 'Netherlands',
      third: 'Brazil',
      finalHome: 3,
      finalAway: 1,
    ),
    (
      year: 1982,
      competition: worldChampionship,
      hosts: ['Spain'],
      champion: 'Italy',
      runnerUp: 'West Germany',
      third: 'Poland',
      finalHome: 3,
      finalAway: 1,
    ),
    (
      year: 1986,
      competition: worldChampionship,
      hosts: ['Mexico'],
      champion: 'Argentina',
      runnerUp: 'West Germany',
      third: 'France',
      finalHome: 3,
      finalAway: 2,
    ),
    (
      year: 1990,
      competition: worldChampionship,
      hosts: ['Italy'],
      champion: 'West Germany',
      runnerUp: 'Argentina',
      third: 'Italy',
      finalHome: 1,
      finalAway: 0,
    ),
    (
      year: 1994,
      competition: worldChampionship,
      hosts: ['United States'],
      champion: 'Brazil',
      runnerUp: 'Italy',
      third: 'Sweden',
      finalHome: 0,
      finalAway: 0,
    ),
    (
      year: 1998,
      competition: worldChampionship,
      hosts: ['France'],
      champion: 'France',
      runnerUp: 'Brazil',
      third: 'Croatia',
      finalHome: 3,
      finalAway: 0,
    ),
    (
      year: 2002,
      competition: worldChampionship,
      hosts: ['Japan'],
      champion: 'Brazil',
      runnerUp: 'Germany',
      third: 'Turkey', // resolves via aliases → Türkiye
      finalHome: 2,
      finalAway: 0,
    ),
    (
      year: 2006,
      competition: worldChampionship,
      hosts: ['Germany'],
      champion: 'Italy',
      runnerUp: 'France',
      third: 'Germany',
      finalHome: 1,
      finalAway: 1,
    ),
    (
      year: 2010,
      competition: worldChampionship,
      hosts: ['South Africa'],
      champion: 'Spain',
      runnerUp: 'Netherlands',
      third: 'Germany',
      finalHome: 1,
      finalAway: 0,
    ),
    (
      year: 2014,
      competition: worldChampionship,
      hosts: ['Brazil'],
      champion: 'Germany',
      runnerUp: 'Argentina',
      third: 'Netherlands',
      finalHome: 1,
      finalAway: 0,
    ),
    (
      year: 2018,
      competition: worldChampionship,
      hosts: ['Russia'],
      champion: 'France',
      runnerUp: 'Croatia',
      third: 'Belgium',
      finalHome: 4,
      finalAway: 2,
    ),
    (
      year: 2022,
      competition: worldChampionship,
      hosts: ['Qatar'],
      champion: 'Argentina',
      runnerUp: 'France',
      third: 'Croatia',
      finalHome: 3,
      finalAway: 3,
    ),
    // 2026 is now seeded as finished, even though a save opens on 1 July
    // 2026 while that World Championship is still being played in reality: a
    // manager opening a new save looks for it in the record, and finding
    // nothing there reads as a hole in the world rather than as a tournament
    // still in progress. Co-hosted by all three of North America's automatic
    // qualifiers.
    (
      year: 2026,
      competition: worldChampionship,
      hosts: ['United States', 'Canada', 'Mexico'],
      champion: 'Spain',
      runnerUp: 'Argentina',
      third: 'France',
      finalHome: 2,
      finalAway: 1,
    ),
    // --- European Championship --------------------------------------------
    (
      year: 1960,
      competition: europeanChampionship,
      hosts: ['France'],
      champion: 'Soviet Union',
      runnerUp: 'Yugoslavia',
      third: null,
      finalHome: 2,
      finalAway: 1,
    ),
    (
      year: 1964,
      competition: europeanChampionship,
      hosts: ['Spain'],
      champion: 'Spain',
      runnerUp: 'Soviet Union',
      third: null,
      finalHome: 2,
      finalAway: 1,
    ),
    (
      year: 1968,
      competition: europeanChampionship,
      hosts: ['Italy'],
      champion: 'Italy',
      runnerUp: 'Yugoslavia',
      third: null,
      finalHome: 2,
      finalAway: 0,
    ),
    (
      year: 1972,
      competition: europeanChampionship,
      hosts: ['Belgium'],
      champion: 'West Germany',
      runnerUp: 'Soviet Union',
      third: null,
      finalHome: 3,
      finalAway: 0,
    ),
    (
      year: 1976,
      competition: europeanChampionship,
      hosts: ['Yugoslavia'],
      champion: 'Czechoslovakia',
      runnerUp: 'West Germany',
      third: null,
      finalHome: 2,
      finalAway: 2,
    ),
    (
      year: 1980,
      competition: europeanChampionship,
      hosts: ['Italy'],
      champion: 'West Germany',
      runnerUp: 'Belgium',
      third: null,
      finalHome: 2,
      finalAway: 1,
    ),
    (
      year: 1984,
      competition: europeanChampionship,
      hosts: ['France'],
      champion: 'France',
      runnerUp: 'Spain',
      third: null,
      finalHome: 2,
      finalAway: 0,
    ),
    (
      year: 1988,
      competition: europeanChampionship,
      hosts: ['West Germany'],
      champion: 'Netherlands',
      runnerUp: 'Soviet Union',
      third: null,
      finalHome: 2,
      finalAway: 0,
    ),
    (
      year: 1992,
      competition: europeanChampionship,
      hosts: ['Sweden'],
      champion: 'Denmark',
      runnerUp: 'Germany',
      third: null,
      finalHome: 2,
      finalAway: 0,
    ),
    (
      year: 1996,
      competition: europeanChampionship,
      hosts: ['England'],
      champion: 'Germany',
      runnerUp: 'Czechia',
      third: null,
      finalHome: 2,
      finalAway: 1,
    ),
    (
      year: 2000,
      competition: europeanChampionship,
      hosts: ['Netherlands'],
      champion: 'France',
      runnerUp: 'Italy',
      third: null,
      finalHome: 2,
      finalAway: 1,
    ),
    (
      year: 2004,
      competition: europeanChampionship,
      hosts: ['Portugal'],
      champion: 'Greece',
      runnerUp: 'Portugal',
      third: null,
      finalHome: 1,
      finalAway: 0,
    ),
    (
      year: 2008,
      competition: europeanChampionship,
      hosts: ['Switzerland'],
      champion: 'Spain',
      runnerUp: 'Germany',
      third: null,
      finalHome: 1,
      finalAway: 0,
    ),
    (
      year: 2012,
      competition: europeanChampionship,
      hosts: ['Poland'],
      champion: 'Spain',
      runnerUp: 'Italy',
      third: null,
      finalHome: 4,
      finalAway: 0,
    ),
    (
      year: 2016,
      competition: europeanChampionship,
      hosts: ['France'],
      champion: 'Portugal',
      runnerUp: 'France',
      third: null,
      finalHome: 1,
      finalAway: 0,
    ),
    (
      year: 2020,
      competition: europeanChampionship,
      hosts: ['England'],
      champion: 'Italy',
      runnerUp: 'England',
      third: null,
      finalHome: 1,
      finalAway: 1,
    ),
    (
      year: 2024,
      competition: europeanChampionship,
      hosts: ['Germany'],
      champion: 'Spain',
      runnerUp: 'England',
      third: null,
      finalHome: 2,
      finalAway: 1,
    ),
    // --- South America Cup -------------------------------------------------
    // The full run of South American Championships / Copa América, back to the
    // first in 1916. Most editions before 1987 were straight round-robins with
    // no final, so they carry a champion and a runner-up but no scoreline; the
    // ones that ended level and went to a play-off record that play-off's
    // score. The 1959 championship was staged twice; only the (official)
    // Argentine edition is listed, since honours are keyed by competition and
    // year and two rows would collide.
    (
      year: 1916,
      competition: southAmericaCup,
      hosts: ['Argentina'],
      champion: 'Uruguay',
      runnerUp: 'Argentina',
      third: null,
      finalHome: null,
      finalAway: null,
    ),
    (
      year: 1917,
      competition: southAmericaCup,
      hosts: ['Uruguay'],
      champion: 'Uruguay',
      runnerUp: 'Argentina',
      third: null,
      finalHome: null,
      finalAway: null,
    ),
    (
      year: 1919,
      competition: southAmericaCup,
      hosts: ['Brazil'],
      champion: 'Brazil',
      runnerUp: 'Uruguay',
      third: null,
      // Level at the top of the table; Brazil won the play-off in extra time.
      finalHome: 1,
      finalAway: 0,
    ),
    (
      year: 1920,
      competition: southAmericaCup,
      hosts: ['Chile'],
      champion: 'Uruguay',
      runnerUp: 'Argentina',
      third: null,
      finalHome: null,
      finalAway: null,
    ),
    (
      year: 1921,
      competition: southAmericaCup,
      hosts: ['Argentina'],
      champion: 'Argentina',
      runnerUp: 'Brazil',
      third: null,
      finalHome: null,
      finalAway: null,
    ),
    (
      year: 1922,
      competition: southAmericaCup,
      hosts: ['Brazil'],
      champion: 'Brazil',
      runnerUp: 'Paraguay',
      third: null,
      // Decided by a play-off after Brazil and Paraguay finished level.
      finalHome: 3,
      finalAway: 0,
    ),
    (
      year: 1923,
      competition: southAmericaCup,
      hosts: ['Uruguay'],
      champion: 'Uruguay',
      runnerUp: 'Argentina',
      third: null,
      finalHome: null,
      finalAway: null,
    ),
    (
      year: 1924,
      competition: southAmericaCup,
      hosts: ['Uruguay'],
      champion: 'Uruguay',
      runnerUp: 'Argentina',
      third: null,
      finalHome: null,
      finalAway: null,
    ),
    (
      year: 1925,
      competition: southAmericaCup,
      hosts: ['Argentina'],
      champion: 'Argentina',
      runnerUp: 'Brazil',
      third: null,
      finalHome: null,
      finalAway: null,
    ),
    (
      year: 1926,
      competition: southAmericaCup,
      hosts: ['Chile'],
      champion: 'Uruguay',
      runnerUp: 'Argentina',
      third: null,
      finalHome: null,
      finalAway: null,
    ),
    (
      year: 1927,
      competition: southAmericaCup,
      hosts: ['Peru'],
      champion: 'Argentina',
      runnerUp: 'Uruguay',
      third: null,
      finalHome: null,
      finalAway: null,
    ),
    (
      year: 1929,
      competition: southAmericaCup,
      hosts: ['Argentina'],
      champion: 'Argentina',
      runnerUp: 'Paraguay',
      third: null,
      finalHome: null,
      finalAway: null,
    ),
    (
      year: 1935,
      competition: southAmericaCup,
      hosts: ['Peru'],
      champion: 'Uruguay',
      runnerUp: 'Argentina',
      third: null,
      finalHome: null,
      finalAway: null,
    ),
    (
      year: 1937,
      competition: southAmericaCup,
      hosts: ['Argentina'],
      champion: 'Argentina',
      runnerUp: 'Brazil',
      third: null,
      // Argentina and Brazil finished level; Argentina took the play-off in
      // extra time.
      finalHome: 2,
      finalAway: 0,
    ),
    (
      year: 1939,
      competition: southAmericaCup,
      hosts: ['Peru'],
      champion: 'Peru',
      runnerUp: 'Uruguay',
      third: null,
      finalHome: null,
      finalAway: null,
    ),
    (
      year: 1941,
      competition: southAmericaCup,
      hosts: ['Chile'],
      champion: 'Argentina',
      runnerUp: 'Uruguay',
      third: null,
      finalHome: null,
      finalAway: null,
    ),
    (
      year: 1942,
      competition: southAmericaCup,
      hosts: ['Uruguay'],
      champion: 'Uruguay',
      runnerUp: 'Argentina',
      third: null,
      finalHome: null,
      finalAway: null,
    ),
    (
      year: 1945,
      competition: southAmericaCup,
      hosts: ['Chile'],
      champion: 'Argentina',
      runnerUp: 'Brazil',
      third: null,
      finalHome: null,
      finalAway: null,
    ),
    (
      year: 1946,
      competition: southAmericaCup,
      hosts: ['Argentina'],
      champion: 'Argentina',
      runnerUp: 'Brazil',
      third: null,
      finalHome: null,
      finalAway: null,
    ),
    (
      year: 1947,
      competition: southAmericaCup,
      hosts: ['Ecuador'],
      champion: 'Argentina',
      runnerUp: 'Paraguay',
      third: null,
      finalHome: null,
      finalAway: null,
    ),
    (
      year: 1949,
      competition: southAmericaCup,
      hosts: ['Brazil'],
      champion: 'Brazil',
      runnerUp: 'Paraguay',
      third: null,
      // Brazil won the play-off after the two finished level.
      finalHome: 7,
      finalAway: 0,
    ),
    (
      year: 1953,
      competition: southAmericaCup,
      hosts: ['Peru'],
      champion: 'Paraguay',
      runnerUp: 'Brazil',
      third: null,
      // Settled by a play-off in Lima.
      finalHome: 3,
      finalAway: 2,
    ),
    (
      year: 1955,
      competition: southAmericaCup,
      hosts: ['Chile'],
      champion: 'Argentina',
      runnerUp: 'Chile',
      third: null,
      finalHome: null,
      finalAway: null,
    ),
    (
      year: 1956,
      competition: southAmericaCup,
      hosts: ['Uruguay'],
      champion: 'Uruguay',
      runnerUp: 'Chile',
      third: null,
      finalHome: null,
      finalAway: null,
    ),
    (
      year: 1957,
      competition: southAmericaCup,
      hosts: ['Peru'],
      champion: 'Argentina',
      runnerUp: 'Brazil',
      third: null,
      finalHome: null,
      finalAway: null,
    ),
    (
      year: 1959,
      competition: southAmericaCup,
      hosts: ['Argentina'],
      champion: 'Argentina',
      runnerUp: 'Brazil',
      third: null,
      finalHome: null,
      finalAway: null,
    ),
    (
      year: 1963,
      competition: southAmericaCup,
      hosts: ['Bolivia'],
      champion: 'Bolivia',
      runnerUp: 'Paraguay',
      third: null,
      finalHome: null,
      finalAway: null,
    ),
    (
      year: 1967,
      competition: southAmericaCup,
      hosts: ['Uruguay'],
      champion: 'Uruguay',
      runnerUp: 'Argentina',
      third: null,
      finalHome: null,
      finalAway: null,
    ),
    // 1975–1983 had no host: the whole tournament was played home-and-away
    // across the continent, so no host country is recorded for them.
    (
      year: 1975,
      competition: southAmericaCup,
      hosts: [''],
      champion: 'Peru',
      runnerUp: 'Colombia',
      third: null,
      // The two-legged final finished level and Peru won the play-off.
      finalHome: 1,
      finalAway: 0,
    ),
    (
      year: 1979,
      competition: southAmericaCup,
      hosts: [''],
      champion: 'Paraguay',
      runnerUp: 'Chile',
      third: null,
      // One win each over the two legs and a goalless play-off; Paraguay took
      // the title on goal difference, so the aggregate is what is recorded (a
      // level score here would read as a shoot-out, which it was not).
      finalHome: 3,
      finalAway: 1,
    ),
    (
      year: 1983,
      competition: southAmericaCup,
      hosts: [''],
      champion: 'Uruguay',
      runnerUp: 'Brazil',
      third: null,
      // Uruguay won the two-legged final 3–1 on aggregate.
      finalHome: 3,
      finalAway: 1,
    ),
    (
      year: 1987,
      competition: southAmericaCup,
      hosts: ['Argentina'],
      champion: 'Uruguay',
      runnerUp: 'Chile',
      third: null,
      finalHome: 1,
      finalAway: 0,
    ),
    (
      year: 1989,
      competition: southAmericaCup,
      hosts: ['Brazil'],
      champion: 'Brazil',
      runnerUp: 'Uruguay',
      third: null,
      // Decided by a final round-robin; Brazil beat Uruguay in the decider.
      finalHome: 1,
      finalAway: 0,
    ),
    (
      year: 1991,
      competition: southAmericaCup,
      hosts: ['Chile'],
      champion: 'Argentina',
      runnerUp: 'Brazil',
      third: null,
      // Also a final round-robin; the two met in the decisive match.
      finalHome: 3,
      finalAway: 2,
    ),
    (
      year: 1993,
      competition: southAmericaCup,
      hosts: ['Ecuador'],
      champion: 'Argentina',
      runnerUp: 'Mexico',
      third: null,
      finalHome: 2,
      finalAway: 1,
    ),
    (
      year: 1995,
      competition: southAmericaCup,
      hosts: ['Uruguay'],
      champion: 'Uruguay',
      runnerUp: 'Brazil',
      third: null,
      finalHome: 1,
      finalAway: 1,
    ),
    (
      year: 1997,
      competition: southAmericaCup,
      hosts: ['Bolivia'],
      champion: 'Brazil',
      runnerUp: 'Bolivia',
      third: null,
      finalHome: 3,
      finalAway: 1,
    ),
    (
      year: 1999,
      competition: southAmericaCup,
      hosts: ['Paraguay'],
      champion: 'Brazil',
      runnerUp: 'Uruguay',
      third: null,
      finalHome: 3,
      finalAway: 0,
    ),
    (
      year: 2001,
      competition: southAmericaCup,
      hosts: ['Colombia'],
      champion: 'Colombia',
      runnerUp: 'Mexico',
      third: null,
      finalHome: 1,
      finalAway: 0,
    ),
    (
      year: 2004,
      competition: southAmericaCup,
      hosts: ['Peru'],
      champion: 'Brazil',
      runnerUp: 'Argentina',
      third: null,
      finalHome: 2,
      finalAway: 2,
    ),
    (
      year: 2007,
      competition: southAmericaCup,
      hosts: ['Venezuela'],
      champion: 'Brazil',
      runnerUp: 'Argentina',
      third: null,
      finalHome: 3,
      finalAway: 0,
    ),
    (
      year: 2011,
      competition: southAmericaCup,
      hosts: ['Argentina'],
      champion: 'Uruguay',
      runnerUp: 'Paraguay',
      third: null,
      finalHome: 3,
      finalAway: 0,
    ),
    (
      year: 2015,
      competition: southAmericaCup,
      hosts: ['Chile'],
      champion: 'Chile',
      runnerUp: 'Argentina',
      third: null,
      finalHome: 0,
      finalAway: 0,
    ),
    (
      year: 2016,
      competition: southAmericaCup,
      hosts: ['United States'],
      champion: 'Chile',
      runnerUp: 'Argentina',
      third: null,
      finalHome: 0,
      finalAway: 0,
    ),
    (
      year: 2019,
      competition: southAmericaCup,
      hosts: ['Brazil'],
      champion: 'Brazil',
      runnerUp: 'Peru',
      third: null,
      finalHome: 3,
      finalAway: 1,
    ),
    (
      year: 2021,
      competition: southAmericaCup,
      hosts: ['Brazil'],
      champion: 'Argentina',
      runnerUp: 'Brazil',
      third: null,
      finalHome: 1,
      finalAway: 0,
    ),
    (
      year: 2024,
      competition: southAmericaCup,
      hosts: ['United States'],
      champion: 'Argentina',
      runnerUp: 'Colombia',
      third: null,
      finalHome: 1,
      finalAway: 0,
    ),
    // --- Nations Cup (UEFA Nations League finals) --------------------------
    // A knock-out final each edition; a level score was settled on penalties.
    (
      year: 2019,
      competition: nationsCup,
      hosts: ['Portugal'],
      champion: 'Portugal',
      runnerUp: 'Netherlands',
      third: 'England',
      finalHome: 1,
      finalAway: 0,
    ),
    (
      year: 2021,
      competition: nationsCup,
      hosts: ['Italy'],
      champion: 'France',
      runnerUp: 'Spain',
      third: 'Italy',
      finalHome: 2,
      finalAway: 1,
    ),
    (
      year: 2023,
      competition: nationsCup,
      hosts: ['Netherlands'],
      champion: 'Spain',
      runnerUp: 'Croatia',
      third: 'Italy',
      // 0–0, Spain won on penalties.
      finalHome: 0,
      finalAway: 0,
    ),
    (
      year: 2025,
      competition: nationsCup,
      hosts: ['Germany'],
      champion: 'Portugal',
      runnerUp: 'Spain',
      third: 'Germany',
      // 2–2, Portugal won on penalties.
      finalHome: 2,
      finalAway: 2,
    ),

    // --- African Championship (Africa Cup of Nations) ----------------------
    (
      year: 2006,
      competition: africanChampionship,
      hosts: ['Egypt'],
      champion: 'Egypt',
      runnerUp: 'Ivory Coast',
      third: 'Nigeria',
      finalHome: 0, // Egypt won on penalties
      finalAway: 0,
    ),
    (
      year: 2008,
      competition: africanChampionship,
      hosts: ['Ghana'],
      champion: 'Egypt',
      runnerUp: 'Cameroon',
      third: 'Ghana',
      finalHome: 1,
      finalAway: 0,
    ),
    (
      year: 2010,
      competition: africanChampionship,
      hosts: ['Angola'],
      champion: 'Egypt',
      runnerUp: 'Ghana',
      third: 'Nigeria',
      finalHome: 1,
      finalAway: 0,
    ),
    (
      year: 2012,
      competition: africanChampionship,
      hosts: ['Gabon'],
      champion: 'Zambia',
      runnerUp: 'Ivory Coast',
      third: 'Mali',
      finalHome: 0, // Zambia won on penalties
      finalAway: 0,
    ),
    (
      year: 2013,
      competition: africanChampionship,
      hosts: ['South Africa'],
      champion: 'Nigeria',
      runnerUp: 'Burkina Faso',
      third: 'Mali',
      finalHome: 1,
      finalAway: 0,
    ),
    (
      year: 2015,
      competition: africanChampionship,
      hosts: ['Equatorial Guinea'],
      champion: 'Ivory Coast',
      runnerUp: 'Ghana',
      third: 'DR Congo',
      finalHome: 0, // Ivory Coast won on penalties
      finalAway: 0,
    ),
    (
      year: 2017,
      competition: africanChampionship,
      hosts: ['Gabon'],
      champion: 'Cameroon',
      runnerUp: 'Egypt',
      third: 'Burkina Faso',
      finalHome: 2,
      finalAway: 1,
    ),
    (
      year: 2019,
      competition: africanChampionship,
      hosts: ['Egypt'],
      champion: 'Algeria',
      runnerUp: 'Senegal',
      third: 'Nigeria',
      finalHome: 1,
      finalAway: 0,
    ),
    (
      year: 2021,
      competition: africanChampionship,
      hosts: ['Cameroon'],
      champion: 'Senegal',
      runnerUp: 'Egypt',
      third: 'Cameroon',
      finalHome: 0, // Senegal won on penalties
      finalAway: 0,
    ),
    (
      year: 2023,
      competition: africanChampionship,
      hosts: ['Ivory Coast'],
      champion: 'Ivory Coast',
      runnerUp: 'Nigeria',
      third: 'South Africa',
      finalHome: 2,
      finalAway: 1,
    ),
    (
      year: 2025,
      competition: africanChampionship,
      hosts: ['Morocco'],
      champion: 'Morocco',
      runnerUp: 'Senegal',
      third: 'Egypt',
      finalHome: 2,
      finalAway: 1,
    ),

    // --- Asian Championship (AFC Asian Cup) --------------------------------
    (
      year: 2000,
      competition: asianChampionship,
      hosts: ['Lebanon'],
      champion: 'Japan',
      runnerUp: 'Saudi Arabia',
      third: 'South Korea',
      finalHome: 1,
      finalAway: 0,
    ),
    (
      year: 2004,
      competition: asianChampionship,
      hosts: ['China PR'],
      champion: 'Japan',
      runnerUp: 'China PR',
      third: 'Iran',
      finalHome: 3,
      finalAway: 1,
    ),
    (
      year: 2007,
      competition: asianChampionship,
      hosts: ['Indonesia'],
      champion: 'Iraq',
      runnerUp: 'Saudi Arabia',
      third: 'South Korea',
      finalHome: 1,
      finalAway: 0,
    ),
    (
      year: 2011,
      competition: asianChampionship,
      hosts: ['Qatar'],
      champion: 'Japan',
      runnerUp: 'Australia',
      third: 'South Korea',
      finalHome: 1,
      finalAway: 0,
    ),
    (
      year: 2015,
      competition: asianChampionship,
      hosts: ['Australia'],
      champion: 'Australia',
      runnerUp: 'South Korea',
      third: 'United Arab Emirates',
      finalHome: 2,
      finalAway: 1,
    ),
    (
      year: 2019,
      competition: asianChampionship,
      hosts: ['United Arab Emirates'],
      champion: 'Qatar',
      runnerUp: 'Japan',
      third: 'Iran',
      finalHome: 3,
      finalAway: 1,
    ),
    (
      year: 2023,
      competition: asianChampionship,
      hosts: ['Qatar'],
      champion: 'Qatar',
      runnerUp: 'Jordan',
      third: 'Iran',
      finalHome: 3,
      finalAway: 1,
    ),

    // --- North America Cup (CONCACAF Gold Cup) -----------------------------
    (
      year: 2009,
      competition: northAmericaCup,
      hosts: ['United States'],
      champion: 'Mexico',
      runnerUp: 'United States',
      third: 'Costa Rica',
      finalHome: 5,
      finalAway: 0,
    ),
    (
      year: 2011,
      competition: northAmericaCup,
      hosts: ['United States'],
      champion: 'Mexico',
      runnerUp: 'United States',
      third: 'Honduras',
      finalHome: 4,
      finalAway: 2,
    ),
    (
      year: 2013,
      competition: northAmericaCup,
      hosts: ['United States'],
      champion: 'United States',
      runnerUp: 'Panama',
      third: 'Honduras',
      finalHome: 1,
      finalAway: 0,
    ),
    (
      year: 2015,
      competition: northAmericaCup,
      hosts: ['Canada'],
      champion: 'Mexico',
      runnerUp: 'Jamaica',
      third: 'Panama',
      finalHome: 3,
      finalAway: 1,
    ),
    (
      year: 2017,
      competition: northAmericaCup,
      hosts: ['United States'],
      champion: 'United States',
      runnerUp: 'Jamaica',
      third: 'Costa Rica',
      finalHome: 2,
      finalAway: 1,
    ),
    (
      year: 2019,
      competition: northAmericaCup,
      hosts: ['United States'],
      champion: 'Mexico',
      runnerUp: 'United States',
      third: 'Haiti',
      finalHome: 1,
      finalAway: 0,
    ),
    (
      year: 2021,
      competition: northAmericaCup,
      hosts: ['United States'],
      champion: 'United States',
      runnerUp: 'Mexico',
      third: 'Canada',
      finalHome: 1,
      finalAway: 0,
    ),
    (
      year: 2023,
      competition: northAmericaCup,
      hosts: ['United States'],
      champion: 'Mexico',
      runnerUp: 'Panama',
      third: 'United States',
      finalHome: 1,
      finalAway: 0,
    ),
    // Biennial, odd years — there was no 2024 edition, so the gap is the
    // tournament's cadence rather than missing data.
    (
      year: 2025,
      competition: northAmericaCup,
      hosts: ['United States'],
      champion: 'Mexico',
      runnerUp: 'United States',
      third: 'Honduras',
      finalHome: 2,
      finalAway: 1,
    ),

    // --- Oceania Cup (OFC Nations Cup) -------------------------------------
    (
      year: 2008,
      competition: oceaniaCup,
      hosts: ['Fiji'],
      champion: 'New Zealand',
      runnerUp: 'New Caledonia',
      third: 'Fiji',
      finalHome: 2,
      finalAway: 0,
    ),
    (
      year: 2012,
      competition: oceaniaCup,
      hosts: ['Solomon Islands'],
      champion: 'Tahiti',
      runnerUp: 'New Caledonia',
      third: 'New Zealand',
      finalHome: 1,
      finalAway: 0,
    ),
    (
      year: 2016,
      competition: oceaniaCup,
      hosts: ['Papua New Guinea'],
      champion: 'New Zealand',
      runnerUp: 'Papua New Guinea',
      third: 'New Caledonia',
      finalHome: 0, // New Zealand won on penalties
      finalAway: 0,
    ),
    // 2020 was cancelled (COVID), so the cup returned in 2024 after an
    // eight-year gap — co-hosted by Fiji and Vanuatu, with the Vanuatu matches
    // ultimately moved to Suva.
    (
      year: 2024,
      competition: oceaniaCup,
      hosts: ['Fiji'],
      champion: 'New Zealand',
      runnerUp: 'Vanuatu',
      third: 'Tahiti', // beat Fiji 2-1 in the third-place match
      finalHome: 3,
      finalAway: 0,
    ),
  ];
}
