/// One real historical tournament final (factual, country-level data only —
/// no player names, to keep the app free of real-person likeness/IP).
///
/// The champion is listed first in the scoreline; equal scores denote a
/// penalty shoot-out win for the champion.
typedef HistoryEdition = ({
  int year,
  String competition,
  String host,
  String champion,
  String runnerUp,
  String? third,
  int finalHome,
  int finalAway,
});

/// Real World Cup, European Championship and South America Cup history, mapped
/// onto the app's tournament names. Used to seed the records section so it is
/// populated from the start of a save.
abstract final class RealHistory {
  /// Maps historical nation names onto their modern equivalent in the data set.
  static const aliases = <String, String>{
    'West Germany': 'Germany',
    'Soviet Union': 'Russia',
    'Czechoslovakia': 'Czechia',
    'Czech Republic': 'Czechia',
    'Yugoslavia': 'Serbia',
  };

  static const worldChampionship = 'World Championship';
  static const europeanChampionship = 'European Championship';
  static const southAmericaCup = 'South America Cup';
  static const nationsCup = 'Nations Cup';

  static const editions = <HistoryEdition>[
    // --- World Cup ---------------------------------------------------------
    (
      year: 1930,
      competition: worldChampionship,
      host: 'Uruguay',
      champion: 'Uruguay',
      runnerUp: 'Argentina',
      third: 'United States',
      finalHome: 4,
      finalAway: 2,
    ),
    (
      year: 1934,
      competition: worldChampionship,
      host: 'Italy',
      champion: 'Italy',
      runnerUp: 'Czechoslovakia',
      third: 'Germany',
      finalHome: 2,
      finalAway: 1,
    ),
    (
      year: 1938,
      competition: worldChampionship,
      host: 'France',
      champion: 'Italy',
      runnerUp: 'Hungary',
      third: 'Brazil',
      finalHome: 4,
      finalAway: 2,
    ),
    (
      year: 1950,
      competition: worldChampionship,
      host: 'Brazil',
      champion: 'Uruguay',
      runnerUp: 'Brazil',
      third: 'Sweden',
      finalHome: 2,
      finalAway: 1,
    ),
    (
      year: 1954,
      competition: worldChampionship,
      host: 'Switzerland',
      champion: 'West Germany',
      runnerUp: 'Hungary',
      third: 'Austria',
      finalHome: 3,
      finalAway: 2,
    ),
    (
      year: 1958,
      competition: worldChampionship,
      host: 'Sweden',
      champion: 'Brazil',
      runnerUp: 'Sweden',
      third: 'France',
      finalHome: 5,
      finalAway: 2,
    ),
    (
      year: 1962,
      competition: worldChampionship,
      host: 'Chile',
      champion: 'Brazil',
      runnerUp: 'Czechoslovakia',
      third: 'Chile',
      finalHome: 3,
      finalAway: 1,
    ),
    (
      year: 1966,
      competition: worldChampionship,
      host: 'England',
      champion: 'England',
      runnerUp: 'West Germany',
      third: 'Portugal',
      finalHome: 4,
      finalAway: 2,
    ),
    (
      year: 1970,
      competition: worldChampionship,
      host: 'Mexico',
      champion: 'Brazil',
      runnerUp: 'Italy',
      third: 'West Germany',
      finalHome: 4,
      finalAway: 1,
    ),
    (
      year: 1974,
      competition: worldChampionship,
      host: 'West Germany',
      champion: 'West Germany',
      runnerUp: 'Netherlands',
      third: 'Poland',
      finalHome: 2,
      finalAway: 1,
    ),
    (
      year: 1978,
      competition: worldChampionship,
      host: 'Argentina',
      champion: 'Argentina',
      runnerUp: 'Netherlands',
      third: 'Brazil',
      finalHome: 3,
      finalAway: 1,
    ),
    (
      year: 1982,
      competition: worldChampionship,
      host: 'Spain',
      champion: 'Italy',
      runnerUp: 'West Germany',
      third: 'Poland',
      finalHome: 3,
      finalAway: 1,
    ),
    (
      year: 1986,
      competition: worldChampionship,
      host: 'Mexico',
      champion: 'Argentina',
      runnerUp: 'West Germany',
      third: 'France',
      finalHome: 3,
      finalAway: 2,
    ),
    (
      year: 1990,
      competition: worldChampionship,
      host: 'Italy',
      champion: 'West Germany',
      runnerUp: 'Argentina',
      third: 'Italy',
      finalHome: 1,
      finalAway: 0,
    ),
    (
      year: 1994,
      competition: worldChampionship,
      host: 'United States',
      champion: 'Brazil',
      runnerUp: 'Italy',
      third: 'Sweden',
      finalHome: 0,
      finalAway: 0,
    ),
    (
      year: 1998,
      competition: worldChampionship,
      host: 'France',
      champion: 'France',
      runnerUp: 'Brazil',
      third: 'Croatia',
      finalHome: 3,
      finalAway: 0,
    ),
    (
      year: 2002,
      competition: worldChampionship,
      host: 'Japan',
      champion: 'Brazil',
      runnerUp: 'Germany',
      third: null,
      finalHome: 2,
      finalAway: 0,
    ),
    (
      year: 2006,
      competition: worldChampionship,
      host: 'Germany',
      champion: 'Italy',
      runnerUp: 'France',
      third: 'Germany',
      finalHome: 1,
      finalAway: 1,
    ),
    (
      year: 2010,
      competition: worldChampionship,
      host: 'South Africa',
      champion: 'Spain',
      runnerUp: 'Netherlands',
      third: 'Germany',
      finalHome: 1,
      finalAway: 0,
    ),
    (
      year: 2014,
      competition: worldChampionship,
      host: 'Brazil',
      champion: 'Germany',
      runnerUp: 'Argentina',
      third: 'Netherlands',
      finalHome: 1,
      finalAway: 0,
    ),
    (
      year: 2018,
      competition: worldChampionship,
      host: 'Russia',
      champion: 'France',
      runnerUp: 'Croatia',
      third: 'Belgium',
      finalHome: 4,
      finalAway: 2,
    ),
    (
      year: 2022,
      competition: worldChampionship,
      host: 'Qatar',
      champion: 'Argentina',
      runnerUp: 'France',
      third: 'Croatia',
      finalHome: 3,
      finalAway: 3,
    ),
    // --- European Championship --------------------------------------------
    (
      year: 1960,
      competition: europeanChampionship,
      host: 'France',
      champion: 'Soviet Union',
      runnerUp: 'Yugoslavia',
      third: null,
      finalHome: 2,
      finalAway: 1,
    ),
    (
      year: 1964,
      competition: europeanChampionship,
      host: 'Spain',
      champion: 'Spain',
      runnerUp: 'Soviet Union',
      third: null,
      finalHome: 2,
      finalAway: 1,
    ),
    (
      year: 1968,
      competition: europeanChampionship,
      host: 'Italy',
      champion: 'Italy',
      runnerUp: 'Yugoslavia',
      third: null,
      finalHome: 2,
      finalAway: 0,
    ),
    (
      year: 1972,
      competition: europeanChampionship,
      host: 'Belgium',
      champion: 'West Germany',
      runnerUp: 'Soviet Union',
      third: null,
      finalHome: 3,
      finalAway: 0,
    ),
    (
      year: 1976,
      competition: europeanChampionship,
      host: 'Yugoslavia',
      champion: 'Czechoslovakia',
      runnerUp: 'West Germany',
      third: null,
      finalHome: 2,
      finalAway: 2,
    ),
    (
      year: 1980,
      competition: europeanChampionship,
      host: 'Italy',
      champion: 'West Germany',
      runnerUp: 'Belgium',
      third: null,
      finalHome: 2,
      finalAway: 1,
    ),
    (
      year: 1984,
      competition: europeanChampionship,
      host: 'France',
      champion: 'France',
      runnerUp: 'Spain',
      third: null,
      finalHome: 2,
      finalAway: 0,
    ),
    (
      year: 1988,
      competition: europeanChampionship,
      host: 'West Germany',
      champion: 'Netherlands',
      runnerUp: 'Soviet Union',
      third: null,
      finalHome: 2,
      finalAway: 0,
    ),
    (
      year: 1992,
      competition: europeanChampionship,
      host: 'Sweden',
      champion: 'Denmark',
      runnerUp: 'Germany',
      third: null,
      finalHome: 2,
      finalAway: 0,
    ),
    (
      year: 1996,
      competition: europeanChampionship,
      host: 'England',
      champion: 'Germany',
      runnerUp: 'Czechia',
      third: null,
      finalHome: 2,
      finalAway: 1,
    ),
    (
      year: 2000,
      competition: europeanChampionship,
      host: 'Netherlands',
      champion: 'France',
      runnerUp: 'Italy',
      third: null,
      finalHome: 2,
      finalAway: 1,
    ),
    (
      year: 2004,
      competition: europeanChampionship,
      host: 'Portugal',
      champion: 'Greece',
      runnerUp: 'Portugal',
      third: null,
      finalHome: 1,
      finalAway: 0,
    ),
    (
      year: 2008,
      competition: europeanChampionship,
      host: 'Switzerland',
      champion: 'Spain',
      runnerUp: 'Germany',
      third: null,
      finalHome: 1,
      finalAway: 0,
    ),
    (
      year: 2012,
      competition: europeanChampionship,
      host: 'Poland',
      champion: 'Spain',
      runnerUp: 'Italy',
      third: null,
      finalHome: 4,
      finalAway: 0,
    ),
    (
      year: 2016,
      competition: europeanChampionship,
      host: 'France',
      champion: 'Portugal',
      runnerUp: 'France',
      third: null,
      finalHome: 1,
      finalAway: 0,
    ),
    (
      year: 2020,
      competition: europeanChampionship,
      host: 'England',
      champion: 'Italy',
      runnerUp: 'England',
      third: null,
      finalHome: 1,
      finalAway: 1,
    ),
    (
      year: 2024,
      competition: europeanChampionship,
      host: 'Germany',
      champion: 'Spain',
      runnerUp: 'England',
      third: null,
      finalHome: 2,
      finalAway: 1,
    ),
    // --- South America Cup -------------------------------------------------
    (
      year: 2011,
      competition: southAmericaCup,
      host: 'Argentina',
      champion: 'Uruguay',
      runnerUp: 'Paraguay',
      third: null,
      finalHome: 3,
      finalAway: 0,
    ),
    (
      year: 2015,
      competition: southAmericaCup,
      host: 'Chile',
      champion: 'Chile',
      runnerUp: 'Argentina',
      third: null,
      finalHome: 0,
      finalAway: 0,
    ),
    (
      year: 2016,
      competition: southAmericaCup,
      host: 'United States',
      champion: 'Chile',
      runnerUp: 'Argentina',
      third: null,
      finalHome: 0,
      finalAway: 0,
    ),
    (
      year: 2019,
      competition: southAmericaCup,
      host: 'Brazil',
      champion: 'Brazil',
      runnerUp: 'Peru',
      third: null,
      finalHome: 3,
      finalAway: 1,
    ),
    (
      year: 2021,
      competition: southAmericaCup,
      host: 'Brazil',
      champion: 'Argentina',
      runnerUp: 'Brazil',
      third: null,
      finalHome: 1,
      finalAway: 0,
    ),
    (
      year: 2024,
      competition: southAmericaCup,
      host: 'United States',
      champion: 'Argentina',
      runnerUp: 'Colombia',
      third: null,
      finalHome: 1,
      finalAway: 0,
    ),
    // --- Nations Cup (UEFA Nations League finals) --------------------------
    // A knock-out final each edition; a level score was settled on penalties.
    (
      year: 2019,
      competition: nationsCup,
      host: 'Portugal',
      champion: 'Portugal',
      runnerUp: 'Netherlands',
      third: 'England',
      finalHome: 1,
      finalAway: 0,
    ),
    (
      year: 2021,
      competition: nationsCup,
      host: 'Italy',
      champion: 'France',
      runnerUp: 'Spain',
      third: 'Italy',
      finalHome: 2,
      finalAway: 1,
    ),
    (
      year: 2023,
      competition: nationsCup,
      host: 'Netherlands',
      champion: 'Spain',
      runnerUp: 'Croatia',
      third: 'Italy',
      // 0–0, Spain won on penalties.
      finalHome: 0,
      finalAway: 0,
    ),
    (
      year: 2025,
      competition: nationsCup,
      host: 'Germany',
      champion: 'Portugal',
      runnerUp: 'Spain',
      third: 'Germany',
      // 2–2, Portugal won on penalties.
      finalHome: 2,
      finalAway: 2,
    ),
  ];
}
