import 'package:fnm/domain/repositories/competition_repository.dart';

/// One group as a ceremony wants it: the group's name and the nations in it,
/// ordered by the pot each came out of.
typedef CeremonyGroup = ({String name, List<int> nationIds});

/// The groups a tournament was ACTUALLY drawn into, read back out of the save.
///
/// Every draw ceremony used to RE-RUN its draw to animate it, on the reasoning
/// that the same seed and the same field give the same groups. They do — while
/// every input still agrees. One of them is the ranking the pots were seeded
/// from, which is snapshotted at the moment of the draw, and a save that has no
/// such snapshot (one made before the slot existed, or one whose draw was
/// generated by an older build) falls back to the static seed ranking. The pots
/// then come out in a different order and the manager watches a ceremony that
/// has nothing to do with the tournament he then plays: not a team out of
/// place, every group different.
///
/// The played groups are stored. Reading them is the one answer that cannot
/// drift, so a ceremony presents the stored draw and only recomputes when there
/// is nothing stored yet.
///
/// [rankById] and [hosts] recover the POT each nation came from, which is all
/// the recomputation was still buying: the real draw fills one team per pot per
/// group, best-ranked first, with any host forced to the top of pot 1 — so
/// within a group, hosts first and the rest by ranking IS pot order. Getting
/// this wrong only mislabels which pot a ball came from; it can no longer put
/// anybody in the wrong group.
List<CeremonyGroup> drawnGroups(
  List<FinalsGroupTable> stored, {
  required Map<int, int> rankById,
  Set<int> hosts = const {},
}) => [
  for (final g in stored)
    (
      name: g.name,
      nationIds: [for (final s in g.standings) s.nationId]..sort((a, b) {
        final ha = hosts.contains(a), hb = hosts.contains(b);
        if (ha != hb) return ha ? -1 : 1;
        return (rankById[a] ?? 9999).compareTo(rankById[b] ?? 9999);
      }),
    ),
];

/// Which pot each nation came out of (1-based), read off [groups] whose nations
/// are already in pot order — the shape [drawnGroups] returns.
Map<int, int> potsFromGroups(List<CeremonyGroup> groups) => {
  for (final g in groups)
    for (var i = 0; i < g.nationIds.length; i++) g.nationIds[i]: i + 1,
};
