import 'package:fnm/domain/entities/enums.dart';

/// Supported team shapes. Each maps to 11 on-pitch positions (slot order:
/// goalkeeper, defence, midfield, attack).
enum Formation {
  f442,
  f433,
  f352,
  f4231,
  f532,
  f4141,
  f343,
  f4222,
  f424,
  f41212,
  f4411,
  f4312,
  f451,
  f541,
  f3421,
  f3412,
  f5212,

  /// The christmas tree.
  f4321,

  /// A back three with a lone striker off a second forward.
  f3511,
}

extension FormationX on Formation {
  /// Human-readable label, e.g. `4-3-3`.
  String get label => switch (this) {
    Formation.f442 => '4-4-2',
    Formation.f433 => '4-3-3',
    Formation.f352 => '3-5-2',
    Formation.f4231 => '4-2-3-1',
    Formation.f532 => '5-3-2',
    Formation.f4141 => '4-1-4-1',
    Formation.f343 => '3-4-3',
    Formation.f4222 => '4-2-2-2',
    Formation.f424 => '4-2-4',
    Formation.f41212 => '4-1-2-1-2',
    Formation.f4411 => '4-4-1-1',
    Formation.f4312 => '4-3-1-2',
    Formation.f451 => '4-5-1',
    Formation.f541 => '5-4-1',
    Formation.f3421 => '3-4-2-1',
    Formation.f3412 => '3-4-1-2',
    Formation.f5212 => '5-2-1-2',
    Formation.f4321 => '4-3-2-1',
    Formation.f3511 => '3-5-1-1',
  };

  /// The 11 positions for this formation, in slot order.
  List<PlayerPosition> get positions => switch (this) {
    Formation.f442 => const [
      PlayerPosition.gk,
      PlayerPosition.lb,
      PlayerPosition.cb,
      PlayerPosition.cb,
      PlayerPosition.rb,
      PlayerPosition.lm,
      PlayerPosition.cm,
      PlayerPosition.cm,
      PlayerPosition.rm,
      PlayerPosition.st,
      PlayerPosition.st,
    ],
    Formation.f433 => const [
      PlayerPosition.gk,
      PlayerPosition.lb,
      PlayerPosition.cb,
      PlayerPosition.cb,
      PlayerPosition.rb,
      PlayerPosition.dm,
      PlayerPosition.cm,
      PlayerPosition.cm,
      PlayerPosition.lw,
      PlayerPosition.st,
      PlayerPosition.rw,
    ],
    Formation.f352 => const [
      PlayerPosition.gk,
      PlayerPosition.cb,
      PlayerPosition.cb,
      PlayerPosition.cb,
      PlayerPosition.lm,
      PlayerPosition.cm,
      PlayerPosition.cm,
      PlayerPosition.cm,
      PlayerPosition.rm,
      PlayerPosition.st,
      PlayerPosition.st,
    ],
    Formation.f4231 => const [
      PlayerPosition.gk,
      PlayerPosition.lb,
      PlayerPosition.cb,
      PlayerPosition.cb,
      PlayerPosition.rb,
      // BOTH holding slots are DM. The "2" of a 4-2-3-1 is a double pivot, and
      // these two sit at the same depth on the pitch (0.38/0.62 at y 0.56) —
      // so declaring one DM and the other CM made mirror-image slots disagree
      // about who fitted them. The same midfielder was in position on one side
      // of the pitch and out of it on the other.
      PlayerPosition.dm,
      PlayerPosition.dm,
      PlayerPosition.am,
      PlayerPosition.lw,
      PlayerPosition.rw,
      PlayerPosition.st,
    ],
    Formation.f532 => const [
      PlayerPosition.gk,
      PlayerPosition.lb,
      PlayerPosition.cb,
      PlayerPosition.cb,
      PlayerPosition.cb,
      PlayerPosition.rb,
      PlayerPosition.cm,
      PlayerPosition.cm,
      PlayerPosition.cm,
      PlayerPosition.st,
      PlayerPosition.st,
    ],
    Formation.f4141 => const [
      PlayerPosition.gk,
      PlayerPosition.lb,
      PlayerPosition.cb,
      PlayerPosition.cb,
      PlayerPosition.rb,
      PlayerPosition.dm,
      PlayerPosition.lm,
      PlayerPosition.cm,
      PlayerPosition.cm,
      PlayerPosition.rm,
      PlayerPosition.st,
    ],
    Formation.f343 => const [
      PlayerPosition.gk,
      PlayerPosition.cb,
      PlayerPosition.cb,
      PlayerPosition.cb,
      PlayerPosition.lm,
      PlayerPosition.cm,
      PlayerPosition.cm,
      PlayerPosition.rm,
      PlayerPosition.lw,
      PlayerPosition.st,
      PlayerPosition.rw,
    ],
    Formation.f4222 => const [
      PlayerPosition.gk,
      PlayerPosition.lb,
      PlayerPosition.cb,
      PlayerPosition.cb,
      PlayerPosition.rb,
      PlayerPosition.dm,
      PlayerPosition.dm,
      PlayerPosition.am,
      PlayerPosition.am,
      PlayerPosition.st,
      PlayerPosition.st,
    ],
    Formation.f424 => const [
      PlayerPosition.gk,
      PlayerPosition.lb,
      PlayerPosition.cb,
      PlayerPosition.cb,
      PlayerPosition.rb,
      PlayerPosition.cm,
      PlayerPosition.cm,
      PlayerPosition.lw,
      PlayerPosition.st,
      PlayerPosition.st,
      PlayerPosition.rw,
    ],
    // 4-1-2-1-2 (the 4-4-2 diamond).
    Formation.f41212 => const [
      PlayerPosition.gk,
      PlayerPosition.lb,
      PlayerPosition.cb,
      PlayerPosition.cb,
      PlayerPosition.rb,
      PlayerPosition.dm,
      PlayerPosition.cm,
      PlayerPosition.cm,
      PlayerPosition.am,
      PlayerPosition.st,
      PlayerPosition.st,
    ],
    Formation.f4411 => const [
      PlayerPosition.gk,
      PlayerPosition.lb,
      PlayerPosition.cb,
      PlayerPosition.cb,
      PlayerPosition.rb,
      PlayerPosition.lm,
      PlayerPosition.cm,
      PlayerPosition.cm,
      PlayerPosition.rm,
      PlayerPosition.am,
      PlayerPosition.st,
    ],
    Formation.f4312 => const [
      PlayerPosition.gk,
      PlayerPosition.lb,
      PlayerPosition.cb,
      PlayerPosition.cb,
      PlayerPosition.rb,
      PlayerPosition.cm,
      PlayerPosition.cm,
      PlayerPosition.cm,
      PlayerPosition.am,
      PlayerPosition.st,
      PlayerPosition.st,
    ],
    Formation.f451 => const [
      PlayerPosition.gk,
      PlayerPosition.lb,
      PlayerPosition.cb,
      PlayerPosition.cb,
      PlayerPosition.rb,
      PlayerPosition.lm,
      PlayerPosition.cm,
      PlayerPosition.cm,
      PlayerPosition.cm,
      PlayerPosition.rm,
      PlayerPosition.st,
    ],
    Formation.f541 => const [
      PlayerPosition.gk,
      PlayerPosition.lb,
      PlayerPosition.cb,
      PlayerPosition.cb,
      PlayerPosition.cb,
      PlayerPosition.rb,
      PlayerPosition.lm,
      PlayerPosition.cm,
      PlayerPosition.cm,
      PlayerPosition.rm,
      PlayerPosition.st,
    ],
    Formation.f3421 => const [
      PlayerPosition.gk,
      PlayerPosition.cb,
      PlayerPosition.cb,
      PlayerPosition.cb,
      PlayerPosition.lm,
      PlayerPosition.cm,
      PlayerPosition.cm,
      PlayerPosition.rm,
      PlayerPosition.am,
      PlayerPosition.am,
      PlayerPosition.st,
    ],
    Formation.f3412 => const [
      PlayerPosition.gk,
      PlayerPosition.cb,
      PlayerPosition.cb,
      PlayerPosition.cb,
      PlayerPosition.lm,
      PlayerPosition.cm,
      PlayerPosition.cm,
      PlayerPosition.rm,
      PlayerPosition.am,
      PlayerPosition.st,
      PlayerPosition.st,
    ],
    Formation.f5212 => const [
      PlayerPosition.gk,
      PlayerPosition.lb,
      PlayerPosition.cb,
      PlayerPosition.cb,
      PlayerPosition.cb,
      PlayerPosition.rb,
      PlayerPosition.cm,
      PlayerPosition.cm,
      PlayerPosition.am,
      PlayerPosition.st,
      PlayerPosition.st,
    ],
    Formation.f4321 => const [
      PlayerPosition.gk,
      PlayerPosition.lb,
      PlayerPosition.cb,
      PlayerPosition.cb,
      PlayerPosition.rb,
      PlayerPosition.cm,
      PlayerPosition.cm,
      PlayerPosition.cm,
      PlayerPosition.am,
      PlayerPosition.am,
      PlayerPosition.st,
    ],
    Formation.f3511 => const [
      PlayerPosition.gk,
      PlayerPosition.cb,
      PlayerPosition.cb,
      PlayerPosition.cb,
      PlayerPosition.lm,
      PlayerPosition.cm,
      PlayerPosition.cm,
      PlayerPosition.cm,
      PlayerPosition.rm,
      PlayerPosition.am,
      PlayerPosition.st,
    ],
  };
}
