/// How a nation's name is WRITTEN, as opposed to what it is called in the seed
/// data.
///
/// The seed file carries one English name per nation and every screen printed
/// it verbatim, which left two problems. A Czech save read a list of English
/// countries — the single most visible thing on almost every screen — and a
/// couple of the English names are the formal ones nobody uses on a scoreboard
/// ("Republic of Ireland").
///
/// Both are display concerns, so they live here rather than in the data: the
/// stored name stays the canonical English one (the real-history seeder and a
/// handful of tests resolve nations by it), and this table is applied when a
/// [Nation] is read out of the database, keyed by FIFA code.
abstract final class NationNames {
  /// The name to print in English, where the seed's formal name is not what a
  /// scoreboard would say.
  static const enByCode = <String, String>{
    'IRL': 'Ireland',
    'CHN': 'China',
    'TPE': 'Taiwan',
  };

  /// The Czech name of each nation, by FIFA code. Nominative case — Czech
  /// declines country names, and a sentence-aware version would need every
  /// string in the app rebuilt around seven forms, so the nominative is used
  /// everywhere and reads correctly in the lists, tables and scoreboards where
  /// a country name is nearly always shown on its own.
  static const csByCode = <String, String>{
    'AFG': 'Afghánistán',
    'AIA': 'Anguilla',
    'ALB': 'Albánie',
    'ALG': 'Alžírsko',
    'AND': 'Andorra',
    'ANG': 'Angola',
    'ARG': 'Argentina',
    'ARM': 'Arménie',
    'ARU': 'Aruba',
    'ASA': 'Americká Samoa',
    'ATG': 'Antigua a Barbuda',
    'AUS': 'Austrálie',
    'AUT': 'Rakousko',
    'AZE': 'Ázerbájdžán',
    'BAH': 'Bahamy',
    'BAN': 'Bangladéš',
    'BDI': 'Burundi',
    'BEL': 'Belgie',
    'BEN': 'Benin',
    'BER': 'Bermudy',
    'BFA': 'Burkina Faso',
    'BHR': 'Bahrajn',
    'BHU': 'Bhútán',
    'BIH': 'Bosna a Hercegovina',
    'BLZ': 'Belize',
    'BOL': 'Bolívie',
    'BOT': 'Botswana',
    'BRA': 'Brazílie',
    'BRB': 'Barbados',
    'BRU': 'Brunej',
    'BUL': 'Bulharsko',
    'CAM': 'Kambodža',
    'CAN': 'Kanada',
    'CAY': 'Kajmanské ostrovy',
    'CGO': 'Kongo',
    'CHA': 'Čad',
    'CHI': 'Chile',
    'CHN': 'Čína',
    'CIV': 'Pobřeží slonoviny',
    'CMR': 'Kamerun',
    'COD': 'DR Kongo',
    'COK': 'Cookovy ostrovy',
    'COL': 'Kolumbie',
    'COM': 'Komory',
    'CPV': 'Kapverdy',
    'CRC': 'Kostarika',
    'CRO': 'Chorvatsko',
    'CTA': 'Středoafrická republika',
    'CUB': 'Kuba',
    'CUW': 'Curaçao',
    'CYP': 'Kypr',
    'CZE': 'Česko',
    'DEN': 'Dánsko',
    'DJI': 'Džibutsko',
    'DMA': 'Dominika',
    'DOM': 'Dominikánská republika',
    'ECU': 'Ekvádor',
    'EGY': 'Egypt',
    'ENG': 'Anglie',
    'EQG': 'Rovníková Guinea',
    'ERI': 'Eritrea',
    'ESP': 'Španělsko',
    'EST': 'Estonsko',
    'ETH': 'Etiopie',
    'FIJ': 'Fidži',
    'FIN': 'Finsko',
    'FRA': 'Francie',
    'FRO': 'Faerské ostrovy',
    'GAB': 'Gabon',
    'GAM': 'Gambie',
    'GEO': 'Gruzie',
    'GER': 'Německo',
    'GHA': 'Ghana',
    'GIB': 'Gibraltar',
    'GNB': 'Guinea-Bissau',
    'GRE': 'Řecko',
    'GRN': 'Grenada',
    'GUA': 'Guatemala',
    'GUI': 'Guinea',
    'GUM': 'Guam',
    'GUY': 'Guyana',
    'HAI': 'Haiti',
    'HKG': 'Hongkong',
    'HON': 'Honduras',
    'HUN': 'Maďarsko',
    'IDN': 'Indonésie',
    'IND': 'Indie',
    'IRL': 'Irsko',
    'IRN': 'Írán',
    'IRQ': 'Irák',
    'ISL': 'Island',
    'ISR': 'Izrael',
    'ITA': 'Itálie',
    'JAM': 'Jamajka',
    'JOR': 'Jordánsko',
    'JPN': 'Japonsko',
    'KAZ': 'Kazachstán',
    'KEN': 'Keňa',
    'KGZ': 'Kyrgyzstán',
    'KOR': 'Jižní Korea',
    'KSA': 'Saúdská Arábie',
    'KUW': 'Kuvajt',
    'KVX': 'Kosovo',
    'LAO': 'Laos',
    'LBR': 'Libérie',
    'LBY': 'Libye',
    'LCA': 'Svatá Lucie',
    'LES': 'Lesotho',
    'LIB': 'Libanon',
    'LIE': 'Lichtenštejnsko',
    'LTU': 'Litva',
    'LUX': 'Lucembursko',
    'LVA': 'Lotyšsko',
    'MAC': 'Macao',
    'MAD': 'Madagaskar',
    'MAR': 'Maroko',
    'MAS': 'Malajsie',
    'MDA': 'Moldavsko',
    'MDV': 'Maledivy',
    'MEX': 'Mexiko',
    'MKD': 'Severní Makedonie',
    'MLI': 'Mali',
    'MLT': 'Malta',
    'MNE': 'Černá Hora',
    'MNG': 'Mongolsko',
    'MOZ': 'Mosambik',
    'MRI': 'Mauricius',
    'MSR': 'Montserrat',
    'MTN': 'Mauritánie',
    'MWI': 'Malawi',
    'MYA': 'Myanmar',
    'NAM': 'Namibie',
    'NCA': 'Nikaragua',
    'NCL': 'Nová Kaledonie',
    'NED': 'Nizozemsko',
    'NEP': 'Nepál',
    'NGA': 'Nigérie',
    'NIG': 'Niger',
    'NIR': 'Severní Irsko',
    'NOR': 'Norsko',
    'NZL': 'Nový Zéland',
    'OMA': 'Omán',
    'PAK': 'Pákistán',
    'PAN': 'Panama',
    'PAR': 'Paraguay',
    'PER': 'Peru',
    'PHI': 'Filipíny',
    'PLE': 'Palestina',
    'PNG': 'Papua-Nová Guinea',
    'POL': 'Polsko',
    'POR': 'Portugalsko',
    'PRK': 'Severní Korea',
    'PUR': 'Portoriko',
    'QAT': 'Katar',
    'ROU': 'Rumunsko',
    'RSA': 'Jihoafrická republika',
    'RWA': 'Rwanda',
    'SAM': 'Samoa',
    'SCO': 'Skotsko',
    'SDN': 'Súdán',
    'SEN': 'Senegal',
    'SEY': 'Seychely',
    'SGP': 'Singapur',
    'SKN': 'Svatý Kryštof a Nevis',
    'SLE': 'Sierra Leone',
    'SLV': 'Salvador',
    'SMR': 'San Marino',
    'SOL': 'Šalomounovy ostrovy',
    'SOM': 'Somálsko',
    'SRB': 'Srbsko',
    'SRI': 'Srí Lanka',
    'SSD': 'Jižní Súdán',
    'STP': 'Svatý Tomáš a Princův ostrov',
    'SUI': 'Švýcarsko',
    'SUR': 'Surinam',
    'SVK': 'Slovensko',
    'SVN': 'Slovinsko',
    'SWE': 'Švédsko',
    'SWZ': 'Eswatini',
    'SYR': 'Sýrie',
    'TAH': 'Tahiti',
    'TAN': 'Tanzanie',
    'TCA': 'Turks a Caicos',
    'TGA': 'Tonga',
    'THA': 'Thajsko',
    'TJK': 'Tádžikistán',
    'TKM': 'Turkmenistán',
    'TLS': 'Východní Timor',
    'TOG': 'Togo',
    'TPE': 'Tchaj-wan',
    'TRI': 'Trinidad a Tobago',
    'TUN': 'Tunisko',
    'TUR': 'Turecko',
    'UAE': 'Spojené arabské emiráty',
    'UGA': 'Uganda',
    'UKR': 'Ukrajina',
    'URU': 'Uruguay',
    'USA': 'USA',
    'UZB': 'Uzbekistán',
    'VAN': 'Vanuatu',
    'VEN': 'Venezuela',
    'VGB': 'Britské Panenské ostrovy',
    'VIE': 'Vietnam',
    'VIN': 'Svatý Vincenc a Grenadiny',
    'VIR': 'Americké Panenské ostrovy',
    'WAL': 'Wales',
    'YEM': 'Jemen',
    'ZAM': 'Zambie',
    'ZIM': 'Zimbabwe',
  };

  /// The DATIVE of each Czech name, by FIFA code — the case that follows
  /// "proti".
  ///
  /// A Czech manager reading "Hrát proti Litva" is reading a machine's Czech.
  /// The preposition governs the dative and the nominative simply cannot
  /// stand there: it is "proti Litvě", "proti Německu", "proti Anglii",
  /// "proti Spojeným státům". English has no cases, so nothing about the
  /// English copy changes; this second column exists only for Czech.
  ///
  /// WRITTEN BY HAND, one code at a time. The patterns take most of it
  /// (-ie → -ii, -sko → -sku, feminine -a → -ě or -e) and then lie about the
  /// rest, and a wrong case reads worse to a native speaker than no
  /// declension at all: Kostarika becomes Kostarice, not "Kostarikě";
  /// Guinea becomes Guineji, not "Guineě"; an adjective in the name declines
  /// with its noun, so Severní Irsko becomes Severnímu Irsku and Nový Zéland
  /// Novému Zélandu; a plural-only name takes -ám or -ům, so Filipíny become
  /// Filipínám and the Kajmanské ostrovy Kajmanským ostrovům.
  ///
  /// The sixteen names in [csIndeclinable] are deliberately IDENTICAL to
  /// their nominative. Anything else that matches its nominative is a hole.
  static const csDativeByCode = <String, String>{
    'AFG': 'Afghánistánu',
    'AIA': 'Anguille',
    'ALB': 'Albánii',
    'ALG': 'Alžírsku',
    'AND': 'Andoře',
    'ANG': 'Angole',
    'ARG': 'Argentině',
    'ARM': 'Arménii',
    'ARU': 'Arubě',
    'ASA': 'Americké Samoe',
    'ATG': 'Antigui a Barbudě',
    'AUS': 'Austrálii',
    'AUT': 'Rakousku',
    'AZE': 'Ázerbájdžánu',
    'BAH': 'Bahamám',
    'BAN': 'Bangladéši',
    'BDI': 'Burundi',
    'BEL': 'Belgii',
    'BEN': 'Beninu',
    'BER': 'Bermudám',
    'BFA': 'Burkině Faso',
    'BHR': 'Bahrajnu',
    'BHU': 'Bhútánu',
    'BIH': 'Bosně a Hercegovině',
    'BLZ': 'Belize',
    'BOL': 'Bolívii',
    'BOT': 'Botswaně',
    'BRA': 'Brazílii',
    'BRB': 'Barbadosu',
    'BRU': 'Bruneji',
    'BUL': 'Bulharsku',
    'CAM': 'Kambodži',
    'CAN': 'Kanadě',
    'CAY': 'Kajmanským ostrovům',
    'CGO': 'Kongu',
    'CHA': 'Čadu',
    'CHI': 'Chile',
    'CHN': 'Číně',
    'CIV': 'Pobřeží slonoviny',
    'CMR': 'Kamerunu',
    'COD': 'DR Kongu',
    'COK': 'Cookovým ostrovům',
    'COL': 'Kolumbii',
    'COM': 'Komorám',
    'CPV': 'Kapverdám',
    'CRC': 'Kostarice',
    'CRO': 'Chorvatsku',
    'CTA': 'Středoafrické republice',
    'CUB': 'Kubě',
    'CUW': 'Curaçau',
    'CYP': 'Kypru',
    'CZE': 'Česku',
    'DEN': 'Dánsku',
    'DJI': 'Džibutsku',
    'DMA': 'Dominice',
    'DOM': 'Dominikánské republice',
    'ECU': 'Ekvádoru',
    'EGY': 'Egyptu',
    'ENG': 'Anglii',
    'EQG': 'Rovníkové Guineji',
    'ERI': 'Eritreji',
    'ESP': 'Španělsku',
    'EST': 'Estonsku',
    'ETH': 'Etiopii',
    'FIJ': 'Fidži',
    'FIN': 'Finsku',
    'FRA': 'Francii',
    'FRO': 'Faerským ostrovům',
    'GAB': 'Gabonu',
    'GAM': 'Gambii',
    'GEO': 'Gruzii',
    'GER': 'Německu',
    'GHA': 'Ghaně',
    'GIB': 'Gibraltaru',
    'GNB': 'Guineji-Bissau',
    'GRE': 'Řecku',
    'GRN': 'Grenadě',
    'GUA': 'Guatemale',
    'GUI': 'Guineji',
    'GUM': 'Guamu',
    'GUY': 'Guyaně',
    'HAI': 'Haiti',
    'HKG': 'Hongkongu',
    'HON': 'Hondurasu',
    'HUN': 'Maďarsku',
    'IDN': 'Indonésii',
    'IND': 'Indii',
    'IRL': 'Irsku',
    'IRN': 'Íránu',
    'IRQ': 'Iráku',
    'ISL': 'Islandu',
    'ISR': 'Izraeli',
    'ITA': 'Itálii',
    'JAM': 'Jamajce',
    'JOR': 'Jordánsku',
    'JPN': 'Japonsku',
    'KAZ': 'Kazachstánu',
    'KEN': 'Keni',
    'KGZ': 'Kyrgyzstánu',
    'KOR': 'Jižní Koreji',
    'KSA': 'Saúdské Arábii',
    'KUW': 'Kuvajtu',
    'KVX': 'Kosovu',
    'LAO': 'Laosu',
    'LBR': 'Libérii',
    'LBY': 'Libyi',
    'LCA': 'Svaté Lucii',
    'LES': 'Lesothu',
    'LIB': 'Libanonu',
    'LIE': 'Lichtenštejnsku',
    'LTU': 'Litvě',
    'LUX': 'Lucembursku',
    'LVA': 'Lotyšsku',
    'MAC': 'Macau',
    'MAD': 'Madagaskaru',
    'MAR': 'Maroku',
    'MAS': 'Malajsii',
    'MDA': 'Moldavsku',
    'MDV': 'Maledivám',
    'MEX': 'Mexiku',
    'MKD': 'Severní Makedonii',
    'MLI': 'Mali',
    'MLT': 'Maltě',
    'MNE': 'Černé Hoře',
    'MNG': 'Mongolsku',
    'MOZ': 'Mosambiku',
    'MRI': 'Mauriciu',
    'MSR': 'Montserratu',
    'MTN': 'Mauritánii',
    'MWI': 'Malawi',
    'MYA': 'Myanmaru',
    'NAM': 'Namibii',
    'NCA': 'Nikaragui',
    'NCL': 'Nové Kaledonii',
    'NED': 'Nizozemsku',
    'NEP': 'Nepálu',
    'NGA': 'Nigérii',
    'NIG': 'Nigeru',
    'NIR': 'Severnímu Irsku',
    'NOR': 'Norsku',
    'NZL': 'Novému Zélandu',
    'OMA': 'Ománu',
    'PAK': 'Pákistánu',
    'PAN': 'Panamě',
    'PAR': 'Paraguayi',
    'PER': 'Peru',
    'PHI': 'Filipínám',
    'PLE': 'Palestině',
    'PNG': 'Papui-Nové Guineji',
    'POL': 'Polsku',
    'POR': 'Portugalsku',
    'PRK': 'Severní Koreji',
    'PUR': 'Portoriku',
    'QAT': 'Kataru',
    'ROU': 'Rumunsku',
    'RSA': 'Jihoafrické republice',
    'RWA': 'Rwandě',
    'SAM': 'Samoe',
    'SCO': 'Skotsku',
    'SDN': 'Súdánu',
    'SEN': 'Senegalu',
    'SEY': 'Seychelám',
    'SGP': 'Singapuru',
    'SKN': 'Svatému Kryštofu a Nevisu',
    'SLE': 'Sierra Leone',
    'SLV': 'Salvadoru',
    'SMR': 'San Marinu',
    'SOL': 'Šalomounovým ostrovům',
    'SOM': 'Somálsku',
    'SRB': 'Srbsku',
    'SRI': 'Srí Lance',
    'SSD': 'Jižnímu Súdánu',
    'STP': 'Svatému Tomáši a Princovu ostrovu',
    'SUI': 'Švýcarsku',
    'SUR': 'Surinamu',
    'SVK': 'Slovensku',
    'SVN': 'Slovinsku',
    'SWE': 'Švédsku',
    'SWZ': 'Eswatini',
    'SYR': 'Sýrii',
    'TAH': 'Tahiti',
    'TAN': 'Tanzanii',
    'TCA': 'Turks a Caicos',
    'TGA': 'Tonze',
    'THA': 'Thajsku',
    'TJK': 'Tádžikistánu',
    'TKM': 'Turkmenistánu',
    'TLS': 'Východnímu Timoru',
    'TOG': 'Togu',
    'TPE': 'Tchaj-wanu',
    'TRI': 'Trinidadu a Tobagu',
    'TUN': 'Tunisku',
    'TUR': 'Turecku',
    'UAE': 'Spojeným arabským emirátům',
    'UGA': 'Ugandě',
    'UKR': 'Ukrajině',
    'URU': 'Uruguayi',
    'USA': 'USA',
    'UZB': 'Uzbekistánu',
    'VAN': 'Vanuatu',
    'VEN': 'Venezuele',
    'VGB': 'Britským Panenským ostrovům',
    'VIE': 'Vietnamu',
    'VIN': 'Svatému Vincenci a Grenadinám',
    'VIR': 'Americkým Panenským ostrovům',
    'WAL': 'Walesu',
    'YEM': 'Jemenu',
    'ZAM': 'Zambii',
    'ZIM': 'Zimbabwe',
  };

  /// The Czech names that do not decline at all, so their dative is their
  /// nominative and that is not an oversight.
  ///
  /// Two kinds. Names Czech has never naturalised and leaves alone — Chile,
  /// Peru, Haiti, Fidži, Mali, Malawi, Burundi, Vanuatu, Tahiti, Eswatini,
  /// Zimbabwe, Belize, Sierra Leone, Turks a Caicos, USA. And one whose head
  /// noun happens to be the same in both cases: Pobřeží slonoviny.
  static const csIndeclinable = <String>{
    'BDI',
    'BLZ',
    'CHI',
    'CIV',
    'FIJ',
    'HAI',
    'MLI',
    'MWI',
    'PER',
    'SLE',
    'SWZ',
    'TAH',
    'TCA',
    'USA',
    'VAN',
    'ZIM',
  };

  /// The name to show for [code] in [languageCode], falling back to the stored
  /// [seedName] for any nation this table has not been taught.
  static String display(String code, String seedName, String languageCode) {
    final key = code.toUpperCase();
    if (languageCode == 'cs') {
      return csByCode[key] ?? enByCode[key] ?? seedName;
    }
    return enByCode[key] ?? seedName;
  }

  /// The name to show for [code] in [languageCode] where the sentence puts it
  /// after "proti" — the dative in Czech, the plain name in English.
  ///
  /// Falls back the same way [display] does, so a nation this table has not
  /// been taught reads as its nominative rather than as nothing.
  static String displayDative(
    String code,
    String seedName,
    String languageCode,
  ) {
    final key = code.toUpperCase();
    if (languageCode == 'cs') {
      return csDativeByCode[key] ?? display(code, seedName, languageCode);
    }
    return display(code, seedName, languageCode);
  }
}
