/// How a nation's name is WRITTEN, as opposed to what it is called in the seed
/// data.
///
/// The seed file carries one English name per nation and every screen printed
/// it verbatim, which left two problems. A Czech save read a list of English
/// countries — the single most visible thing on almost every screen — and a
/// couple of the English names are the formal ones nobody uses on a scoreboard
/// ("Republic of Ireland").
///
/// Both are display concerns, so they live here rather than in the data: the
/// stored name stays the canonical English one (the real-history seeder and a
/// handful of tests resolve nations by it), and this table is applied when a
/// [Nation] is read out of the database, keyed by FIFA code.
abstract final class NationNames {
  /// The name to print in English, where the seed's formal name is not what a
  /// scoreboard would say.
  static const enByCode = <String, String>{
    'IRL': 'Ireland',
    'CHN': 'China',
    'TPE': 'Taiwan',
  };

  /// The Czech name of each nation, by FIFA code. Nominative case — Czech
  /// declines country names, and a sentence-aware version would need every
  /// string in the app rebuilt around seven forms, so the nominative is used
  /// everywhere and reads correctly in the lists, tables and scoreboards where
  /// a country name is nearly always shown on its own.
  static const csByCode = <String, String>{
    'AFG': 'Afghánistán',
    'AIA': 'Anguilla',
    'ALB': 'Albánie',
    'ALG': 'Alžírsko',
    'AND': 'Andorra',
    'ANG': 'Angola',
    'ARG': 'Argentina',
    'ARM': 'Arménie',
    'ARU': 'Aruba',
    'ASA': 'Americká Samoa',
    'ATG': 'Antigua a Barbuda',
    'AUS': 'Austrálie',
    'AUT': 'Rakousko',
    'AZE': 'Ázerbájdžán',
    'BAH': 'Bahamy',
    'BAN': 'Bangladéš',
    'BDI': 'Burundi',
    'BEL': 'Belgie',
    'BEN': 'Benin',
    'BER': 'Bermudy',
    'BFA': 'Burkina Faso',
    'BHR': 'Bahrajn',
    'BHU': 'Bhútán',
    'BIH': 'Bosna a Hercegovina',
    'BLZ': 'Belize',
    'BOL': 'Bolívie',
    'BOT': 'Botswana',
    'BRA': 'Brazílie',
    'BRB': 'Barbados',
    'BRU': 'Brunej',
    'BUL': 'Bulharsko',
    'CAM': 'Kambodža',
    'CAN': 'Kanada',
    'CAY': 'Kajmanské ostrovy',
    'CGO': 'Kongo',
    'CHA': 'Čad',
    'CHI': 'Chile',
    'CHN': 'Čína',
    'CIV': 'Pobřeží slonoviny',
    'CMR': 'Kamerun',
    'COD': 'DR Kongo',
    'COK': 'Cookovy ostrovy',
    'COL': 'Kolumbie',
    'COM': 'Komory',
    'CPV': 'Kapverdy',
    'CRC': 'Kostarika',
    'CRO': 'Chorvatsko',
    'CTA': 'Středoafrická republika',
    'CUB': 'Kuba',
    'CUW': 'Curaçao',
    'CYP': 'Kypr',
    'CZE': 'Česko',
    'DEN': 'Dánsko',
    'DJI': 'Džibutsko',
    'DMA': 'Dominika',
    'DOM': 'Dominikánská republika',
    'ECU': 'Ekvádor',
    'EGY': 'Egypt',
    'ENG': 'Anglie',
    'EQG': 'Rovníková Guinea',
    'ERI': 'Eritrea',
    'ESP': 'Španělsko',
    'EST': 'Estonsko',
    'ETH': 'Etiopie',
    'FIJ': 'Fidži',
    'FIN': 'Finsko',
    'FRA': 'Francie',
    'FRO': 'Faerské ostrovy',
    'GAB': 'Gabon',
    'GAM': 'Gambie',
    'GEO': 'Gruzie',
    'GER': 'Německo',
    'GHA': 'Ghana',
    'GIB': 'Gibraltar',
    'GNB': 'Guinea-Bissau',
    'GRE': 'Řecko',
    'GRN': 'Grenada',
    'GUA': 'Guatemala',
    'GUI': 'Guinea',
    'GUM': 'Guam',
    'GUY': 'Guyana',
    'HAI': 'Haiti',
    'HKG': 'Hongkong',
    'HON': 'Honduras',
    'HUN': 'Maďarsko',
    'IDN': 'Indonésie',
    'IND': 'Indie',
    'IRL': 'Irsko',
    'IRN': 'Írán',
    'IRQ': 'Irák',
    'ISL': 'Island',
    'ISR': 'Izrael',
    'ITA': 'Itálie',
    'JAM': 'Jamajka',
    'JOR': 'Jordánsko',
    'JPN': 'Japonsko',
    'KAZ': 'Kazachstán',
    'KEN': 'Keňa',
    'KGZ': 'Kyrgyzstán',
    'KOR': 'Jižní Korea',
    'KSA': 'Saúdská Arábie',
    'KUW': 'Kuvajt',
    'KVX': 'Kosovo',
    'LAO': 'Laos',
    'LBR': 'Libérie',
    'LBY': 'Libye',
    'LCA': 'Svatá Lucie',
    'LES': 'Lesotho',
    'LIB': 'Libanon',
    'LIE': 'Lichtenštejnsko',
    'LTU': 'Litva',
    'LUX': 'Lucembursko',
    'LVA': 'Lotyšsko',
    'MAC': 'Macao',
    'MAD': 'Madagaskar',
    'MAR': 'Maroko',
    'MAS': 'Malajsie',
    'MDA': 'Moldavsko',
    'MDV': 'Maledivy',
    'MEX': 'Mexiko',
    'MKD': 'Severní Makedonie',
    'MLI': 'Mali',
    'MLT': 'Malta',
    'MNE': 'Černá Hora',
    'MNG': 'Mongolsko',
    'MOZ': 'Mosambik',
    'MRI': 'Mauricius',
    'MSR': 'Montserrat',
    'MTN': 'Mauritánie',
    'MWI': 'Malawi',
    'MYA': 'Myanmar',
    'NAM': 'Namibie',
    'NCA': 'Nikaragua',
    'NCL': 'Nová Kaledonie',
    'NED': 'Nizozemsko',
    'NEP': 'Nepál',
    'NGA': 'Nigérie',
    'NIG': 'Niger',
    'NIR': 'Severní Irsko',
    'NOR': 'Norsko',
    'NZL': 'Nový Zéland',
    'OMA': 'Omán',
    'PAK': 'Pákistán',
    'PAN': 'Panama',
    'PAR': 'Paraguay',
    'PER': 'Peru',
    'PHI': 'Filipíny',
    'PLE': 'Palestina',
    'PNG': 'Papua-Nová Guinea',
    'POL': 'Polsko',
    'POR': 'Portugalsko',
    'PRK': 'Severní Korea',
    'PUR': 'Portoriko',
    'QAT': 'Katar',
    'ROU': 'Rumunsko',
    'RSA': 'Jihoafrická republika',
    'RWA': 'Rwanda',
    'SAM': 'Samoa',
    'SCO': 'Skotsko',
    'SDN': 'Súdán',
    'SEN': 'Senegal',
    'SEY': 'Seychely',
    'SGP': 'Singapur',
    'SKN': 'Svatý Kryštof a Nevis',
    'SLE': 'Sierra Leone',
    'SLV': 'Salvador',
    'SMR': 'San Marino',
    'SOL': 'Šalomounovy ostrovy',
    'SOM': 'Somálsko',
    'SRB': 'Srbsko',
    'SRI': 'Srí Lanka',
    'SSD': 'Jižní Súdán',
    'STP': 'Svatý Tomáš a Princův ostrov',
    'SUI': 'Švýcarsko',
    'SUR': 'Surinam',
    'SVK': 'Slovensko',
    'SVN': 'Slovinsko',
    'SWE': 'Švédsko',
    'SWZ': 'Eswatini',
    'SYR': 'Sýrie',
    'TAH': 'Tahiti',
    'TAN': 'Tanzanie',
    'TCA': 'Turks a Caicos',
    'TGA': 'Tonga',
    'THA': 'Thajsko',
    'TJK': 'Tádžikistán',
    'TKM': 'Turkmenistán',
    'TLS': 'Východní Timor',
    'TOG': 'Togo',
    'TPE': 'Tchaj-wan',
    'TRI': 'Trinidad a Tobago',
    'TUN': 'Tunisko',
    'TUR': 'Turecko',
    'UAE': 'Spojené arabské emiráty',
    'UGA': 'Uganda',
    'UKR': 'Ukrajina',
    'URU': 'Uruguay',
    'USA': 'USA',
    'UZB': 'Uzbekistán',
    'VAN': 'Vanuatu',
    'VEN': 'Venezuela',
    'VGB': 'Britské Panenské ostrovy',
    'VIE': 'Vietnam',
    'VIN': 'Svatý Vincenc a Grenadiny',
    'VIR': 'Americké Panenské ostrovy',
    'WAL': 'Wales',
    'YEM': 'Jemen',
    'ZAM': 'Zambie',
    'ZIM': 'Zimbabwe',
  };

  /// The name to show for [code] in [languageCode], falling back to the stored
  /// [seedName] for any nation this table has not been taught.
  static String display(String code, String seedName, String languageCode) {
    final key = code.toUpperCase();
    if (languageCode == 'cs') {
      return csByCode[key] ?? enByCode[key] ?? seedName;
    }
    return enByCode[key] ?? seedName;
  }
}
