/// Geographic subregion of each national team, used to pick tournament
/// co-hosts that are genuine neighbours (same subregion). Keyed by nation
/// code. Grouped by real geography, not football confederation.
abstract final class NationGeography {
  static const subregionByCode = <String, String>{
    // --- Europe & Mediterranean ---
    'ALB': 'balkans',
    'AND': 'iberia',
    'ARM': 'caucasus',
    'AUT': 'centralEurope',
    'AZE': 'caucasus',
    'BEL': 'westEurope',
    'BIH': 'balkans',
    'BUL': 'balkans',
    'CRO': 'balkans',
    'CYP': 'anatolia',
    'CZE': 'centralEurope',
    'DEN': 'scandinavia',
    'ENG': 'britishIsles',
    'EST': 'baltics',
    'FRO': 'scandinavia',
    'FIN': 'scandinavia',
    'FRA': 'westEurope',
    'GEO': 'caucasus',
    'GER': 'centralEurope',
    'GIB': 'iberia',
    'GRE': 'balkans',
    'HUN': 'centralEurope',
    'ISL': 'scandinavia',
    'ISR': 'levant',
    'ITA': 'italyMalta',
    'KAZ': 'centralAsia',
    'KVX': 'balkans',
    'LVA': 'baltics',
    'LIE': 'centralEurope',
    'LTU': 'baltics',
    'LUX': 'westEurope',
    'MLT': 'italyMalta',
    'MDA': 'easternEurope',
    'MNE': 'balkans',
    'NED': 'westEurope',
    'MKD': 'balkans',
    'NIR': 'britishIsles',
    'NOR': 'scandinavia',
    'POL': 'centralEurope',
    'POR': 'iberia',
    'IRL': 'britishIsles',
    'ROU': 'easternEurope',
    'SMR': 'italyMalta',
    'SCO': 'britishIsles',
    'SRB': 'balkans',
    'SVK': 'centralEurope',
    'SVN': 'balkans',
    'ESP': 'iberia',
    'SWE': 'scandinavia',
    'SUI': 'centralEurope',
    'TUR': 'anatolia',
    'UKR': 'easternEurope',
    'WAL': 'britishIsles',

    // --- South America ---
    'ARG': 'southernCone',
    'BOL': 'andean',
    'BRA': 'southernCone',
    'CHI': 'southernCone',
    'COL': 'northSouthAmerica',
    'ECU': 'northSouthAmerica',
    'PAR': 'southernCone',
    'PER': 'andean',
    'URU': 'southernCone',
    'VEN': 'northSouthAmerica',

    // --- North & Central America, Caribbean ---
    'AIA': 'caribbean',
    'ATG': 'caribbean',
    'ARU': 'caribbean',
    'BAH': 'caribbean',
    'BRB': 'caribbean',
    'BLZ': 'centralAmerica',
    'BER': 'caribbean',
    'VGB': 'caribbean',
    'CAN': 'northAmericaMainland',
    'CAY': 'caribbean',
    'CRC': 'centralAmerica',
    'CUB': 'caribbean',
    'CUW': 'caribbean',
    'DMA': 'caribbean',
    'DOM': 'caribbean',
    'SLV': 'centralAmerica',
    'GRN': 'caribbean',
    'GUA': 'centralAmerica',
    'GUY': 'northSouthAmerica',
    'HAI': 'caribbean',
    'HON': 'centralAmerica',
    'JAM': 'caribbean',
    'MEX': 'northAmericaMainland',
    'MSR': 'caribbean',
    'NCA': 'centralAmerica',
    'PAN': 'centralAmerica',
    'PUR': 'caribbean',
    'SKN': 'caribbean',
    'LCA': 'caribbean',
    'VIN': 'caribbean',
    'SUR': 'northSouthAmerica',
    'TRI': 'caribbean',
    'TCA': 'caribbean',
    'USA': 'northAmericaMainland',
    'VIR': 'caribbean',

    // --- Africa ---
    'ALG': 'northAfrica',
    'ANG': 'centralAfrica',
    'BEN': 'westAfrica',
    'BOT': 'southernAfrica',
    'BFA': 'sahel',
    'BDI': 'eastAfrica',
    'CMR': 'centralAfrica',
    'CPV': 'westAfrica',
    'CTA': 'centralAfrica',
    'CHA': 'sahel',
    'COM': 'indianOcean',
    'CGO': 'centralAfrica',
    'COD': 'centralAfrica',
    'DJI': 'hornAfrica',
    'EGY': 'northAfrica',
    'EQG': 'centralAfrica',
    'ERI': 'hornAfrica',
    'SWZ': 'southernAfrica',
    'ETH': 'hornAfrica',
    'GAB': 'centralAfrica',
    'GAM': 'westAfrica',
    'GHA': 'westAfrica',
    'GUI': 'westAfrica',
    'GNB': 'westAfrica',
    'CIV': 'westAfrica',
    'KEN': 'eastAfrica',
    'LES': 'southernAfrica',
    'LBR': 'westAfrica',
    'LBY': 'northAfrica',
    'MAD': 'indianOcean',
    'MWI': 'southernAfrica',
    'MLI': 'sahel',
    'MTN': 'sahel',
    'MRI': 'indianOcean',
    'MAR': 'northAfrica',
    'MOZ': 'southernAfrica',
    'NAM': 'southernAfrica',
    'NIG': 'sahel',
    'NGA': 'westAfrica',
    'RWA': 'eastAfrica',
    'STP': 'centralAfrica',
    'SEN': 'westAfrica',
    'SEY': 'indianOcean',
    'SLE': 'westAfrica',
    'SOM': 'hornAfrica',
    'RSA': 'southernAfrica',
    'SSD': 'hornAfrica',
    'SDN': 'hornAfrica',
    'TAN': 'eastAfrica',
    'TOG': 'westAfrica',
    'TUN': 'northAfrica',
    'UGA': 'eastAfrica',
    'ZAM': 'southernAfrica',
    'ZIM': 'southernAfrica',

    // --- Asia ---
    'AFG': 'centralAsia',
    'AUS': 'australasia',
    'BHR': 'gulf',
    'BAN': 'southAsia',
    'BHU': 'southAsia',
    'BRU': 'southeastAsia',
    'CAM': 'southeastAsia',
    'CHN': 'eastAsia',
    'TPE': 'eastAsia',
    'GUM': 'micronesia',
    'HKG': 'eastAsia',
    'IND': 'southAsia',
    'IDN': 'southeastAsia',
    'IRN': 'gulf',
    'IRQ': 'gulf',
    'JPN': 'eastAsia',
    'JOR': 'levant',
    'KUW': 'gulf',
    'KGZ': 'centralAsia',
    'LAO': 'southeastAsia',
    'LIB': 'levant',
    'MAC': 'eastAsia',
    'MAS': 'southeastAsia',
    'MDV': 'southAsia',
    'MNG': 'eastAsia',
    'MYA': 'southeastAsia',
    'NEP': 'southAsia',
    'PRK': 'eastAsia',
    'OMA': 'gulf',
    'PAK': 'southAsia',
    'PLE': 'levant',
    'PHI': 'southeastAsia',
    'QAT': 'gulf',
    'KSA': 'gulf',
    'SGP': 'southeastAsia',
    'KOR': 'eastAsia',
    'SRI': 'southAsia',
    'SYR': 'levant',
    'TJK': 'centralAsia',
    'THA': 'southeastAsia',
    'TLS': 'southeastAsia',
    'TKM': 'centralAsia',
    'UAE': 'gulf',
    'UZB': 'centralAsia',
    'VIE': 'southeastAsia',
    'YEM': 'gulf',

    // --- Oceania ---
    'ASA': 'polynesia',
    'COK': 'polynesia',
    'FIJ': 'polynesia',
    'NCL': 'australasia',
    'NZL': 'australasia',
    'PNG': 'melanesia',
    'SAM': 'polynesia',
    'SOL': 'melanesia',
    'TAH': 'polynesia',
    'TGA': 'polynesia',
    'VAN': 'melanesia',
  };

  /// The subregion for [code], falling back to [fallback] (e.g. the
  /// confederation name) when a code is unmapped.
  static String subregionFor(String code, String fallback) =>
      subregionByCode[code.toUpperCase()] ?? fallback;
}
