// The full FIFA nation table used to generate the seed data.
//
// Each entry carries a `strength` (0-100 squad quality) that drives both the
// derived FIFA ranking (nations are sorted by strength) and the overall
// ratings of that nation's generated players, plus a `culture` key selecting a
// name pool (see name_pools.dart). Strength/ranking values are plausible
// approximations, not official figures.
//
// The four free-demo nations (Brazil, France, Spain, England) are flagged.
import 'package:fnm/domain/entities/enums.dart';

class NationSeed {
  const NationSeed(
    this.name,
    this.code,
    this.confederation,
    this.strength,
    this.culture, {
    this.isFreeDemo = false,
  });

  final String name;
  final String code;
  final Confederation confederation;
  final int strength;
  final String culture;
  final bool isFreeDemo;
}

const Confederation _eu = Confederation.europe;
const Confederation _sa = Confederation.southAmerica;
const Confederation _na = Confederation.northAmerica;
const Confederation _af = Confederation.africa;
const Confederation _as = Confederation.asia;
const Confederation _oc = Confederation.oceania;

const List<NationSeed> fifaNations = [
  // ── UEFA / Europe (55) ──────────────────────────────────────────────
  NationSeed('Albania', 'ALB', _eu, 64, 'balkan'),
  NationSeed('Andorra', 'AND', _eu, 30, 'spanish'),
  NationSeed('Armenia', 'ARM', _eu, 55, 'slavic'),
  NationSeed('Austria', 'AUT', _eu, 80, 'german'),
  NationSeed('Azerbaijan', 'AZE', _eu, 52, 'turkic'),
  NationSeed('Belgium', 'BEL', _eu, 86, 'dutch'),
  NationSeed('Bosnia and Herzegovina', 'BIH', _eu, 68, 'balkan'),
  NationSeed('Bulgaria', 'BUL', _eu, 60, 'slavic'),
  NationSeed('Croatia', 'CRO', _eu, 84, 'balkan'),
  NationSeed('Cyprus', 'CYP', _eu, 50, 'greek'),
  NationSeed('Czechia', 'CZE', _eu, 74, 'slavic'),
  NationSeed('Denmark', 'DEN', _eu, 83, 'nordic'),
  NationSeed('England', 'ENG', _eu, 90, 'english', isFreeDemo: true),
  NationSeed('Estonia', 'EST', _eu, 46, 'nordic'),
  NationSeed('Faroe Islands', 'FRO', _eu, 34, 'nordic'),
  NationSeed('Finland', 'FIN', _eu, 64, 'nordic'),
  NationSeed('France', 'FRA', _eu, 92, 'french', isFreeDemo: true),
  NationSeed('Georgia', 'GEO', _eu, 60, 'slavic'),
  NationSeed('Germany', 'GER', _eu, 88, 'german'),
  NationSeed('Gibraltar', 'GIB', _eu, 30, 'english'),
  NationSeed('Greece', 'GRE', _eu, 68, 'greek'),
  NationSeed('Hungary', 'HUN', _eu, 70, 'slavic'),
  NationSeed('Iceland', 'ISL', _eu, 60, 'nordic'),
  NationSeed('Israel', 'ISR', _eu, 62, 'arabic'),
  NationSeed('Italy', 'ITA', _eu, 86, 'italian'),
  NationSeed('Kazakhstan', 'KAZ', _eu, 48, 'turkic'),
  NationSeed('Kosovo', 'KVX', _eu, 58, 'balkan'),
  NationSeed('Latvia', 'LVA', _eu, 44, 'nordic'),
  NationSeed('Liechtenstein', 'LIE', _eu, 28, 'german'),
  NationSeed('Lithuania', 'LTU', _eu, 44, 'nordic'),
  NationSeed('Luxembourg', 'LUX', _eu, 50, 'french'),
  NationSeed('Malta', 'MLT', _eu, 38, 'italian'),
  NationSeed('Moldova', 'MDA', _eu, 46, 'slavic'),
  NationSeed('Montenegro', 'MNE', _eu, 58, 'balkan'),
  NationSeed('Netherlands', 'NED', _eu, 88, 'dutch'),
  NationSeed('North Macedonia', 'MKD', _eu, 60, 'balkan'),
  NationSeed('Northern Ireland', 'NIR', _eu, 58, 'english'),
  NationSeed('Norway', 'NOR', _eu, 76, 'nordic'),
  NationSeed('Poland', 'POL', _eu, 76, 'slavic'),
  NationSeed('Portugal', 'POR', _eu, 90, 'portuguese'),
  NationSeed('Republic of Ireland', 'IRL', _eu, 64, 'english'),
  NationSeed('Romania', 'ROU', _eu, 66, 'slavic'),
  NationSeed('San Marino', 'SMR', _eu, 22, 'italian'),
  NationSeed('Scotland', 'SCO', _eu, 70, 'english'),
  NationSeed('Serbia', 'SRB', _eu, 78, 'balkan'),
  NationSeed('Slovakia', 'SVK', _eu, 66, 'slavic'),
  NationSeed('Slovenia', 'SVN', _eu, 66, 'balkan'),
  NationSeed('Spain', 'ESP', _eu, 90, 'spanish', isFreeDemo: true),
  NationSeed('Sweden', 'SWE', _eu, 74, 'nordic'),
  NationSeed('Switzerland', 'SUI', _eu, 80, 'german'),
  NationSeed('Türkiye', 'TUR', _eu, 76, 'turkic'),
  NationSeed('Ukraine', 'UKR', _eu, 74, 'slavic'),
  NationSeed('Wales', 'WAL', _eu, 68, 'english'),

  // ── CONMEBOL / South America (10) ───────────────────────────────────
  NationSeed('Argentina', 'ARG', _sa, 93, 'spanish'),
  NationSeed('Bolivia', 'BOL', _sa, 52, 'spanish'),
  NationSeed('Brazil', 'BRA', _sa, 92, 'portuguese', isFreeDemo: true),
  NationSeed('Chile', 'CHI', _sa, 70, 'spanish'),
  NationSeed('Colombia', 'COL', _sa, 84, 'spanish'),
  NationSeed('Ecuador', 'ECU', _sa, 72, 'spanish'),
  NationSeed('Paraguay', 'PAR', _sa, 66, 'spanish'),
  NationSeed('Peru', 'PER', _sa, 68, 'spanish'),
  NationSeed('Uruguay', 'URU', _sa, 84, 'spanish'),
  NationSeed('Venezuela', 'VEN', _sa, 64, 'spanish'),

  // ── CONCACAF / North America (35) ───────────────────────────────────
  NationSeed('Anguilla', 'AIA', _na, 26, 'english'),
  NationSeed('Antigua and Barbuda', 'ATG', _na, 40, 'english'),
  NationSeed('Aruba', 'ARU', _na, 32, 'dutch'),
  NationSeed('Bahamas', 'BAH', _na, 30, 'english'),
  NationSeed('Barbados', 'BRB', _na, 38, 'english'),
  NationSeed('Belize', 'BLZ', _na, 36, 'spanish'),
  NationSeed('Bermuda', 'BER', _na, 40, 'english'),
  NationSeed('British Virgin Islands', 'VGB', _na, 24, 'english'),
  NationSeed('Canada', 'CAN', _na, 78, 'english'),
  NationSeed('Cayman Islands', 'CAY', _na, 26, 'english'),
  NationSeed('Costa Rica', 'CRC', _na, 72, 'spanish'),
  NationSeed('Cuba', 'CUB', _na, 48, 'spanish'),
  NationSeed('Curaçao', 'CUW', _na, 56, 'dutch'),
  NationSeed('Dominica', 'DMA', _na, 28, 'english'),
  NationSeed('Dominican Republic', 'DOM', _na, 50, 'spanish'),
  NationSeed('El Salvador', 'SLV', _na, 50, 'spanish'),
  NationSeed('Grenada', 'GRN', _na, 36, 'english'),
  NationSeed('Guatemala', 'GUA', _na, 52, 'spanish'),
  NationSeed('Guyana', 'GUY', _na, 40, 'english'),
  NationSeed('Haiti', 'HAI', _na, 58, 'french'),
  NationSeed('Honduras', 'HON', _na, 60, 'spanish'),
  NationSeed('Jamaica', 'JAM', _na, 66, 'english'),
  NationSeed('Mexico', 'MEX', _na, 82, 'spanish'),
  NationSeed('Montserrat', 'MSR', _na, 22, 'english'),
  NationSeed('Nicaragua', 'NCA', _na, 42, 'spanish'),
  NationSeed('Panama', 'PAN', _na, 64, 'spanish'),
  NationSeed('Puerto Rico', 'PUR', _na, 36, 'spanish'),
  NationSeed('Saint Kitts and Nevis', 'SKN', _na, 36, 'english'),
  NationSeed('Saint Lucia', 'LCA', _na, 30, 'english'),
  NationSeed('St Vincent and the Grenadines', 'VIN', _na, 32, 'english'),
  NationSeed('Suriname', 'SUR', _na, 54, 'dutch'),
  NationSeed('Trinidad and Tobago', 'TRI', _na, 58, 'english'),
  NationSeed('Turks and Caicos Islands', 'TCA', _na, 20, 'english'),
  NationSeed('United States', 'USA', _na, 80, 'english'),
  NationSeed('US Virgin Islands', 'VIR', _na, 22, 'english'),

  // ── CAF / Africa (54) ───────────────────────────────────────────────
  NationSeed('Algeria', 'ALG', _af, 78, 'arabic'),
  NationSeed('Angola', 'ANG', _af, 58, 'portuguese'),
  NationSeed('Benin', 'BEN', _af, 56, 'westAfrican'),
  NationSeed('Botswana', 'BOT', _af, 44, 'bantu'),
  NationSeed('Burkina Faso', 'BFA', _af, 66, 'westAfrican'),
  NationSeed('Burundi', 'BDI', _af, 44, 'bantu'),
  NationSeed('Cameroon', 'CMR', _af, 74, 'westAfrican'),
  NationSeed('Cape Verde', 'CPV', _af, 60, 'portuguese'),
  NationSeed('Central African Republic', 'CTA', _af, 42, 'westAfrican'),
  NationSeed('Chad', 'CHA', _af, 34, 'arabic'),
  NationSeed('Comoros', 'COM', _af, 44, 'arabic'),
  NationSeed('Congo', 'CGO', _af, 52, 'westAfrican'),
  NationSeed('DR Congo', 'COD', _af, 70, 'westAfrican'),
  NationSeed('Djibouti', 'DJI', _af, 28, 'arabic'),
  NationSeed('Egypt', 'EGY', _af, 78, 'arabic'),
  NationSeed('Equatorial Guinea', 'EQG', _af, 48, 'westAfrican'),
  NationSeed('Eritrea', 'ERI', _af, 30, 'arabic'),
  NationSeed('Eswatini', 'SWZ', _af, 36, 'bantu'),
  NationSeed('Ethiopia', 'ETH', _af, 44, 'bantu'),
  NationSeed('Gabon', 'GAB', _af, 58, 'westAfrican'),
  NationSeed('Gambia', 'GAM', _af, 52, 'westAfrican'),
  NationSeed('Ghana', 'GHA', _af, 76, 'westAfrican'),
  NationSeed('Guinea', 'GUI', _af, 64, 'westAfrican'),
  NationSeed('Guinea-Bissau', 'GNB', _af, 54, 'portuguese'),
  NationSeed('Ivory Coast', 'CIV', _af, 78, 'westAfrican'),
  NationSeed('Kenya', 'KEN', _af, 50, 'bantu'),
  NationSeed('Lesotho', 'LES', _af, 34, 'bantu'),
  NationSeed('Liberia', 'LBR', _af, 46, 'westAfrican'),
  NationSeed('Libya', 'LBY', _af, 48, 'arabic'),
  NationSeed('Madagascar', 'MAD', _af, 48, 'bantu'),
  NationSeed('Malawi', 'MWI', _af, 40, 'bantu'),
  NationSeed('Mali', 'MLI', _af, 70, 'westAfrican'),
  NationSeed('Mauritania', 'MTN', _af, 50, 'arabic'),
  NationSeed('Mauritius', 'MRI', _af, 30, 'bantu'),
  NationSeed('Morocco', 'MAR', _af, 84, 'arabic'),
  NationSeed('Mozambique', 'MOZ', _af, 48, 'portuguese'),
  NationSeed('Namibia', 'NAM', _af, 46, 'bantu'),
  NationSeed('Niger', 'NIG', _af, 44, 'westAfrican'),
  NationSeed('Nigeria', 'NGA', _af, 78, 'westAfrican'),
  NationSeed('Rwanda', 'RWA', _af, 44, 'bantu'),
  NationSeed('São Tomé and Príncipe', 'STP', _af, 26, 'portuguese'),
  NationSeed('Senegal', 'SEN', _af, 82, 'westAfrican'),
  NationSeed('Seychelles', 'SEY', _af, 24, 'bantu'),
  NationSeed('Sierra Leone', 'SLE', _af, 48, 'westAfrican'),
  NationSeed('Somalia', 'SOM', _af, 26, 'arabic'),
  NationSeed('South Africa', 'RSA', _af, 64, 'bantu'),
  NationSeed('South Sudan', 'SSD', _af, 30, 'bantu'),
  NationSeed('Sudan', 'SDN', _af, 46, 'arabic'),
  NationSeed('Tanzania', 'TAN', _af, 48, 'bantu'),
  NationSeed('Togo', 'TOG', _af, 52, 'westAfrican'),
  NationSeed('Tunisia', 'TUN', _af, 74, 'arabic'),
  NationSeed('Uganda', 'UGA', _af, 50, 'bantu'),
  NationSeed('Zambia', 'ZAM', _af, 54, 'bantu'),
  NationSeed('Zimbabwe', 'ZIM', _af, 50, 'bantu'),

  // ── AFC / Asia (47) ─────────────────────────────────────────────────
  NationSeed('Afghanistan', 'AFG', _as, 36, 'southAsian'),
  NationSeed('Australia', 'AUS', _as, 80, 'english'),
  NationSeed('Bahrain', 'BHR', _as, 54, 'arabic'),
  NationSeed('Bangladesh', 'BAN', _as, 34, 'southAsian'),
  NationSeed('Bhutan', 'BHU', _as, 22, 'southAsian'),
  NationSeed('Brunei', 'BRU', _as, 26, 'southeastAsian'),
  NationSeed('Cambodia', 'CAM', _as, 36, 'southeastAsian'),
  NationSeed('China PR', 'CHN', _as, 62, 'eastAsian'),
  NationSeed('Chinese Taipei', 'TPE', _as, 32, 'eastAsian'),
  NationSeed('Guam', 'GUM', _as, 24, 'pacific'),
  NationSeed('Hong Kong', 'HKG', _as, 44, 'eastAsian'),
  NationSeed('India', 'IND', _as, 52, 'southAsian'),
  NationSeed('Indonesia', 'IDN', _as, 50, 'southeastAsian'),
  NationSeed('Iran', 'IRN', _as, 80, 'arabic'),
  NationSeed('Iraq', 'IRQ', _as, 66, 'arabic'),
  NationSeed('Japan', 'JPN', _as, 82, 'eastAsian'),
  NationSeed('Jordan', 'JOR', _as, 60, 'arabic'),
  NationSeed('Kuwait', 'KUW', _as, 46, 'arabic'),
  NationSeed('Kyrgyzstan', 'KGZ', _as, 44, 'turkic'),
  NationSeed('Laos', 'LAO', _as, 28, 'southeastAsian'),
  NationSeed('Lebanon', 'LIB', _as, 50, 'arabic'),
  NationSeed('Macau', 'MAC', _as, 22, 'eastAsian'),
  NationSeed('Malaysia', 'MAS', _as, 48, 'southeastAsian'),
  NationSeed('Maldives', 'MDV', _as, 30, 'southAsian'),
  NationSeed('Mongolia', 'MNG', _as, 28, 'eastAsian'),
  NationSeed('Myanmar', 'MYA', _as, 38, 'southeastAsian'),
  NationSeed('Nepal', 'NEP', _as, 34, 'southAsian'),
  NationSeed('North Korea', 'PRK', _as, 52, 'eastAsian'),
  NationSeed('Oman', 'OMA', _as, 56, 'arabic'),
  NationSeed('Pakistan', 'PAK', _as, 32, 'southAsian'),
  NationSeed('Palestine', 'PLE', _as, 50, 'arabic'),
  NationSeed('Philippines', 'PHI', _as, 42, 'southeastAsian'),
  NationSeed('Qatar', 'QAT', _as, 68, 'arabic'),
  NationSeed('Saudi Arabia', 'KSA', _as, 72, 'arabic'),
  NationSeed('Singapore', 'SGP', _as, 40, 'southeastAsian'),
  NationSeed('South Korea', 'KOR', _as, 82, 'eastAsian'),
  NationSeed('Sri Lanka', 'SRI', _as, 28, 'southAsian'),
  NationSeed('Syria', 'SYR', _as, 54, 'arabic'),
  NationSeed('Tajikistan', 'TJK', _as, 46, 'turkic'),
  NationSeed('Thailand', 'THA', _as, 54, 'southeastAsian'),
  NationSeed('Timor-Leste', 'TLS', _as, 22, 'southeastAsian'),
  NationSeed('Turkmenistan', 'TKM', _as, 38, 'turkic'),
  NationSeed('United Arab Emirates', 'UAE', _as, 64, 'arabic'),
  NationSeed('Uzbekistan', 'UZB', _as, 66, 'turkic'),
  NationSeed('Vietnam', 'VIE', _as, 54, 'southeastAsian'),
  NationSeed('Yemen', 'YEM', _as, 34, 'arabic'),

  // ── OFC / Oceania (11) ──────────────────────────────────────────────
  NationSeed('American Samoa', 'ASA', _oc, 18, 'pacific'),
  NationSeed('Cook Islands', 'COK', _oc, 20, 'pacific'),
  NationSeed('Fiji', 'FIJ', _oc, 44, 'pacific'),
  NationSeed('New Caledonia', 'NCL', _oc, 42, 'french'),
  NationSeed('New Zealand', 'NZL', _oc, 64, 'english'),
  NationSeed('Papua New Guinea', 'PNG', _oc, 36, 'pacific'),
  NationSeed('Samoa', 'SAM', _oc, 26, 'pacific'),
  NationSeed('Solomon Islands', 'SOL', _oc, 40, 'pacific'),
  NationSeed('Tahiti', 'TAH', _oc, 38, 'french'),
  NationSeed('Tonga', 'TGA', _oc, 22, 'pacific'),
  NationSeed('Vanuatu', 'VAN', _oc, 28, 'pacific'),
];
